import type { Problem } from "@/lib/problems";

// The original Easy problems.
export const EASY_PROBLEMS: Problem[] = [
  {
    slug: "two-sum",
    title: "Two Sum",
    difficulty: "Easy",
    topics: ["Arrays", "Hash map"],
    summary: "Find the two numbers that add up to a target.",
    description: [
      "Given an array of integers `nums` and an integer `target`, return the indices of the two numbers that add up to `target`.",
      "Every input has exactly one valid answer, and you may not use the same element twice. Return the two indices in increasing order.",
    ],
    constraints: [
      "`2 <= nums.length <= 10^4`",
      "`-10^9 <= nums[i], target <= 10^9`",
      "Exactly one valid answer exists.",
    ],
    hint: "For each number, the partner you need is `target - number`. A hash map from value to index lets you check for it in constant time.",
    functionName: { js: "twoSum", py: "two_sum" },
    params: [
      { name: "nums", type: "int[]" },
      { name: "target", type: "int" },
    ],
    returns: "int[]",
    tests: [
      { args: [[2, 7, 11, 15], 9], expected: [0, 1], example: true, explanation: "nums[0] + nums[1] = 2 + 7 = 9." },
      { args: [[3, 2, 4], 6], expected: [1, 2], example: true },
      { args: [[3, 3], 6], expected: [0, 1], example: true },
      { args: [[-1, -2, -3, -4, -5], -8], expected: [2, 4] },
      { args: [[0, 4, 3, 0], 0], expected: [0, 3] },
      { args: [[1, 5, 9, 14, 20], 34], expected: [3, 4] },
      { args: [[5, 75, 25], 100], expected: [1, 2] },
    ],
  },
  {
    slug: "valid-parentheses",
    title: "Valid Parentheses",
    difficulty: "Easy",
    topics: ["Strings", "Stack"],
    summary: "Check whether every bracket is closed in the right order.",
    description: [
      "Given a string `s` made up only of the characters `(`, `)`, `{`, `}`, `[` and `]`, decide whether it is valid.",
      "A string is valid when every opening bracket is closed by the same type of bracket, brackets close in the correct order, and every closing bracket has a matching opening bracket.",
    ],
    constraints: ["`1 <= s.length <= 10^4`", "`s` contains only the six bracket characters."],
    hint: "Push each opening bracket onto a stack. When you see a closing bracket, the top of the stack must be its matching opener.",
    functionName: { js: "isValid", py: "is_valid" },
    params: [{ name: "s", type: "str" }],
    returns: "bool",
    tests: [
      { args: ["()"], expected: true, example: true },
      { args: ["()[]{}"], expected: true, example: true },
      { args: ["(]"], expected: false, example: true },
      { args: ["([)]"], expected: false },
      { args: ["{[]}"], expected: true },
      { args: ["(("], expected: false },
      { args: ["){"], expected: false },
      { args: ["[({})]"], expected: true },
    ],
  },
  {
    slug: "valid-anagram",
    title: "Valid Anagram",
    difficulty: "Easy",
    topics: ["Strings", "Hash map"],
    summary: "Decide whether two words use exactly the same letters.",
    description: [
      "Given two strings `s` and `t`, return `true` if `t` is an anagram of `s`, and `false` otherwise.",
      "An anagram uses exactly the same letters as the original, the same number of times, possibly in a different order.",
    ],
    constraints: ["`1 <= s.length, t.length <= 5 * 10^4`", "`s` and `t` contain only lowercase English letters."],
    hint: "Count how many times each letter appears in `s`, then subtract the counts for `t`. Every count should end at zero.",
    functionName: { js: "isAnagram", py: "is_anagram" },
    params: [
      { name: "s", type: "str" },
      { name: "t", type: "str" },
    ],
    returns: "bool",
    tests: [
      { args: ["anagram", "nagaram"], expected: true, example: true },
      { args: ["rat", "car"], expected: false, example: true },
      { args: ["a", "a"], expected: true },
      { args: ["ab", "a"], expected: false },
      { args: ["listen", "silent"], expected: true },
      { args: ["aacc", "ccac"], expected: false },
    ],
  },
  {
    slug: "binary-search",
    title: "Binary Search",
    difficulty: "Easy",
    topics: ["Arrays", "Binary search"],
    summary: "Find a target in a sorted array in logarithmic time.",
    description: [
      "Given an array of integers `nums` sorted in ascending order and an integer `target`, return the index of `target` in `nums`, or `-1` if it isn't there.",
      "All values in `nums` are distinct. Aim for an `O(log n)` solution.",
    ],
    constraints: ["`1 <= nums.length <= 10^4`", "`-10^4 < nums[i], target < 10^4`", "`nums` is sorted in ascending order with no duplicates."],
    hint: "Compare `target` with the middle element. Each comparison lets you throw away half of the remaining range.",
    functionName: { js: "search", py: "search" },
    params: [
      { name: "nums", type: "int[]" },
      { name: "target", type: "int" },
    ],
    returns: "int",
    tests: [
      { args: [[-1, 0, 3, 5, 9, 12], 9], expected: 4, example: true, explanation: "9 is at index 4." },
      { args: [[-1, 0, 3, 5, 9, 12], 2], expected: -1, example: true, explanation: "2 isn't in the array." },
      { args: [[5], 5], expected: 0 },
      { args: [[5], -5], expected: -1 },
      { args: [[1, 3, 5, 7, 9, 11], 1], expected: 0 },
      { args: [[1, 3, 5, 7, 9, 11], 11], expected: 5 },
      { args: [[2, 4, 6, 8], 5], expected: -1 },
    ],
  },
  {
    slug: "best-time-to-buy-and-sell-stock",
    title: "Best Time to Buy and Sell Stock",
    difficulty: "Easy",
    topics: ["Arrays", "Greedy"],
    summary: "Pick one day to buy and a later day to sell for the biggest profit.",
    description: [
      "You're given an array `prices` where `prices[i]` is a stock's price on day `i`. Choose one day to buy and a **later** day to sell.",
      "Return the largest profit you can make. If no trade makes money, return `0`.",
    ],
    constraints: ["`1 <= prices.length <= 10^5`", "`0 <= prices[i] <= 10^4`"],
    hint: "Scan the days once, remembering the cheapest price so far. Each day, the best sale is today's price minus that minimum.",
    functionName: { js: "maxProfit", py: "max_profit" },
    params: [{ name: "prices", type: "int[]" }],
    returns: "int",
    tests: [
      { args: [[7, 1, 5, 3, 6, 4]], expected: 5, example: true, explanation: "Buy at 1 (day 1) and sell at 6 (day 4)." },
      { args: [[7, 6, 4, 3, 1]], expected: 0, example: true, explanation: "Prices only fall, so the best move is not to trade." },
      { args: [[1]], expected: 0 },
      { args: [[2, 4, 1]], expected: 2 },
      { args: [[3, 3, 5, 0, 0, 3, 1, 4]], expected: 4 },
      { args: [[1, 2, 3, 4, 5]], expected: 4 },
      { args: [[2, 1, 2, 1, 0, 1, 2]], expected: 2 },
    ],
  },
  {
    slug: "valid-palindrome",
    title: "Valid Palindrome",
    difficulty: "Easy",
    topics: ["Strings", "Two pointers"],
    summary: "Check whether a phrase reads the same both ways, ignoring punctuation.",
    description: [
      "A phrase is a palindrome if, after converting uppercase letters to lowercase and removing everything that isn't a letter or a digit, it reads the same forwards and backwards.",
      "Given a string `s`, return `true` if it is a palindrome and `false` otherwise.",
    ],
    constraints: ["`1 <= s.length <= 2 * 10^5`", "`s` contains printable ASCII characters."],
    hint: "Use two pointers from both ends. Skip anything that isn't a letter or digit, and compare the rest case-insensitively.",
    functionName: { js: "isPalindrome", py: "is_palindrome" },
    params: [{ name: "s", type: "str" }],
    returns: "bool",
    tests: [
      {
        args: ["A man, a plan, a canal: Panama"],
        expected: true,
        example: true,
        explanation: "After cleanup it reads \"amanaplanacanalpanama\" both ways.",
      },
      { args: ["race a car"], expected: false, example: true },
      {
        args: [" "],
        expected: true,
        example: true,
        explanation: "After cleanup the string is empty, which counts as a palindrome.",
      },
      { args: ["0P"], expected: false },
      { args: ["No 'x' in Nixon"], expected: true },
      { args: ["ab_a"], expected: true },
      { args: ["Madam, I'm Adam"], expected: true },
    ],
  },
  {
    slug: "climbing-stairs",
    title: "Climbing Stairs",
    difficulty: "Easy",
    topics: ["Dynamic programming", "Math"],
    summary: "Count the ways to climb a staircase one or two steps at a time.",
    description: [
      "You're climbing a staircase with `n` steps. With each move you can climb either 1 or 2 steps.",
      "Return the number of distinct ways to reach the top.",
    ],
    constraints: ["`1 <= n <= 45`"],
    hint: "To reach step `n`, your last move came from step `n - 1` or step `n - 2`. So the ways to reach `n` are the sum of the ways to reach those two.",
    functionName: { js: "climbStairs", py: "climb_stairs" },
    params: [{ name: "n", type: "int" }],
    returns: "int",
    tests: [
      { args: [2], expected: 2, example: true, explanation: "1 step + 1 step, or 2 steps at once." },
      { args: [3], expected: 3, example: true, explanation: "1 + 1 + 1, 1 + 2, or 2 + 1." },
      { args: [1], expected: 1 },
      { args: [5], expected: 8 },
      { args: [10], expected: 89 },
      { args: [45], expected: 1836311903 },
    ],
  },
  {
    slug: "missing-number",
    title: "Missing Number",
    difficulty: "Easy",
    topics: ["Arrays", "Math"],
    summary: "Find the one number missing from a range.",
    description: [
      "The array `nums` contains `n` distinct numbers taken from the range `0` to `n`, so exactly one number in that range is missing.",
      "Return the missing number.",
    ],
    constraints: ["`1 <= nums.length <= 10^4`", "`0 <= nums[i] <= n`", "All numbers in `nums` are distinct."],
    hint: "The numbers from `0` to `n` add up to `n * (n + 1) / 2`. Subtract the actual sum of `nums` from that.",
    functionName: { js: "missingNumber", py: "missing_number" },
    params: [{ name: "nums", type: "int[]" }],
    returns: "int",
    tests: [
      { args: [[3, 0, 1]], expected: 2, example: true, explanation: "n = 3, so the range is 0 to 3, and 2 is missing." },
      { args: [[0, 1]], expected: 2, example: true },
      { args: [[9, 6, 4, 2, 3, 5, 7, 0, 1]], expected: 8, example: true },
      { args: [[0]], expected: 1 },
      { args: [[1]], expected: 0 },
      { args: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]], expected: 0 },
    ],
  },
  {
    slug: "first-unique-character",
    title: "First Unique Character",
    difficulty: "Easy",
    topics: ["Strings", "Hash map"],
    summary: "Find the first character that appears only once.",
    description: [
      "Given a string `s`, return the index of the first character that appears exactly once in it.",
      "If every character repeats, return `-1`.",
    ],
    constraints: ["`1 <= s.length <= 10^5`", "`s` contains only lowercase English letters."],
    hint: "Make one pass to count every character, then a second pass to find the first one with a count of 1.",
    functionName: { js: "firstUniqChar", py: "first_uniq_char" },
    params: [{ name: "s", type: "str" }],
    returns: "int",
    tests: [
      { args: ["swiss"], expected: 1, example: true, explanation: "'w' is the first character that appears only once." },
      { args: ["aabb"], expected: -1, example: true },
      { args: ["codeshare"], expected: 0, example: true },
      { args: ["z"], expected: 0 },
      { args: ["abcabcd"], expected: 6 },
      { args: ["xxyzz"], expected: 2 },
    ],
  },
  {
    slug: "roman-to-integer",
    title: "Roman to Integer",
    difficulty: "Easy",
    topics: ["Strings", "Math", "Hash map"],
    summary: "Convert a Roman numeral into a number.",
    description: [
      "Roman numerals use seven symbols: `I` = 1, `V` = 5, `X` = 10, `L` = 50, `C` = 100, `D` = 500 and `M` = 1000.",
      "Symbols are usually written from largest to smallest and added together. When a smaller symbol comes right before a larger one, it is subtracted instead: `IV` = 4, `IX` = 9, `XL` = 40, `XC` = 90, `CD` = 400 and `CM` = 900.",
      "Given a valid Roman numeral `s`, return its value.",
    ],
    constraints: ["`1 <= s.length <= 15`", "`s` is a valid Roman numeral between 1 and 3999."],
    hint: "Read left to right. If a symbol is smaller than the one after it, subtract it; otherwise add it.",
    functionName: { js: "romanToInt", py: "roman_to_int" },
    params: [{ name: "s", type: "str" }],
    returns: "int",
    tests: [
      { args: ["III"], expected: 3, example: true },
      { args: ["LVIII"], expected: 58, example: true, explanation: "L = 50, V = 5, III = 3." },
      { args: ["MCMXCIV"], expected: 1994, example: true, explanation: "M = 1000, CM = 900, XC = 90, IV = 4." },
      { args: ["IX"], expected: 9 },
      { args: ["XL"], expected: 40 },
      { args: ["MMMCMXCIX"], expected: 3999 },
      { args: ["CDXLIV"], expected: 444 },
    ],
  },
  {
    slug: "single-number",
    title: "Single Number",
    difficulty: "Easy",
    topics: ["Bit manipulation", "Arrays"],
    summary: "Every number appears twice except one. Find it.",
    description: [
      "Every element of the integer array `nums` appears exactly twice, except for one element that appears once. Return that single element.",
      "Aim for linear time and constant extra space.",
    ],
    constraints: ["`1 <= nums.length <= 3 * 10^4`", "`-3 * 10^4 <= nums[i] <= 3 * 10^4`"],
    hint: "XOR has two handy properties: `x ^ x = 0` and `x ^ 0 = x`. XOR everything together and the pairs cancel out.",
    functionName: { js: "singleNumber", py: "single_number" },
    params: [{ name: "nums", type: "int[]" }],
    returns: "int",
    tests: [
      { args: [[2, 2, 1]], expected: 1, example: true },
      { args: [[4, 1, 2, 1, 2]], expected: 4, example: true },
      { args: [[1]], expected: 1, example: true },
      { args: [[-1, -1, -2]], expected: -2 },
      { args: [[0, 7, 7]], expected: 0 },
      { args: [[9, 3, 5, 3, 9]], expected: 5 },
    ],
  },
  {
    slug: "counting-bits",
    title: "Counting Bits",
    difficulty: "Easy",
    topics: ["Bit manipulation", "Dynamic programming"],
    summary: "Count the 1s in the binary form of every number up to n.",
    description: [
      "Given an integer `n`, return an array `ans` of length `n + 1` where `ans[i]` is the number of `1` bits in the binary representation of `i`.",
    ],
    constraints: ["`0 <= n <= 10^5`"],
    hint: "`i` has the same bits as `i >> 1` (that is, `i` divided by 2), plus one more if `i` is odd. So `ans[i] = ans[i >> 1] + (i & 1)`.",
    functionName: { js: "countBits", py: "count_bits" },
    params: [{ name: "n", type: "int" }],
    returns: "int[]",
    tests: [
      { args: [2], expected: [0, 1, 1], example: true, explanation: "0 is 0, 1 is 1 and 2 is 10 in binary." },
      { args: [5], expected: [0, 1, 1, 2, 1, 2], example: true },
      { args: [0], expected: [0] },
      { args: [1], expected: [0, 1] },
      { args: [8], expected: [0, 1, 1, 2, 1, 2, 2, 3, 1] },
      { args: [15], expected: [0, 1, 1, 2, 1, 2, 2, 3, 1, 2, 2, 3, 2, 3, 3, 4] },
    ],
  },
  {
    slug: "move-zeroes",
    title: "Move Zeroes",
    difficulty: "Easy",
    topics: ["Arrays", "Two pointers"],
    summary: "Shift every zero to the end while keeping the other numbers in order.",
    description: [
      "Given an integer array `nums`, move all the `0`s to the end while keeping the relative order of the non-zero numbers.",
      "Do this **in place**: change `nums` directly instead of returning a new array. The tests check `nums` after your function finishes.",
    ],
    constraints: ["`1 <= nums.length <= 10^4`", "`-2^31 <= nums[i] <= 2^31 - 1`"],
    hint: "Keep a write position. Copy each non-zero number to the write position as you scan, then fill the remaining slots with zeros.",
    functionName: { js: "moveZeroes", py: "move_zeroes" },
    params: [{ name: "nums", type: "int[]" }],
    returns: "void",
    outputArg: 0,
    tests: [
      {
        args: [[0, 1, 0, 3, 12]],
        expected: [1, 3, 12, 0, 0],
        example: true,
        explanation: "The non-zero numbers keep their order: 1, 3, 12.",
      },
      { args: [[0]], expected: [0], example: true },
      { args: [[1, 2, 3]], expected: [1, 2, 3] },
      { args: [[0, 0, 1]], expected: [1, 0, 0] },
      { args: [[4, 0, 5, 0, 0, 6]], expected: [4, 5, 6, 0, 0, 0] },
      { args: [[-1, 0, -2, 0]], expected: [-1, -2, 0, 0] },
    ],
  },
  {
    slug: "reverse-linked-list",
    title: "Reverse Linked List",
    difficulty: "Easy",
    topics: ["Linked list"],
    summary: "Reverse the direction of a singly linked list.",
    description: [
      "Given the `head` of a singly linked list, reverse the list and return the new head.",
      "Lists are written as arrays in the examples: `[1, 2, 3]` means `1 → 2 → 3`, and `[]` is an empty list (a `null` head).",
    ],
    constraints: ["The list has between `0` and `5000` nodes.", "`-5000 <= Node.val <= 5000`"],
    hint: "Walk the list once, pointing each node's `next` back at the previous node. Keep track of `prev`, `current` and the next node before you overwrite the link.",
    functionName: { js: "reverseList", py: "reverse_list" },
    params: [{ name: "head", type: "list" }],
    returns: "list",
    tests: [
      { args: [[1, 2, 3, 4, 5]], expected: [5, 4, 3, 2, 1], example: true },
      { args: [[1, 2]], expected: [2, 1], example: true },
      { args: [[]], expected: [], example: true },
      { args: [[7]], expected: [7] },
      { args: [[1, 1, 2, 2]], expected: [2, 2, 1, 1] },
      { args: [[-3, 0, 3]], expected: [3, 0, -3] },
    ],
  },
  {
    slug: "merge-two-sorted-lists",
    title: "Merge Two Sorted Lists",
    difficulty: "Easy",
    topics: ["Linked list", "Two pointers"],
    summary: "Splice two sorted linked lists into one sorted list.",
    description: [
      "You're given the heads of two sorted linked lists, `list1` and `list2`. Merge them into one sorted list by splicing their nodes together, and return its head.",
      "Lists are written as arrays: `[1, 2, 4]` means `1 → 2 → 4`.",
    ],
    constraints: [
      "Each list has between `0` and `50` nodes.",
      "`-100 <= Node.val <= 100`",
      "Both lists are sorted in non-decreasing order.",
    ],
    hint: "Start from a dummy node and keep attaching the smaller of the two current heads. When one list runs out, attach the rest of the other.",
    functionName: { js: "mergeTwoLists", py: "merge_two_lists" },
    params: [
      { name: "list1", type: "list" },
      { name: "list2", type: "list" },
    ],
    returns: "list",
    tests: [
      { args: [[1, 2, 4], [1, 3, 4]], expected: [1, 1, 2, 3, 4, 4], example: true },
      { args: [[], []], expected: [], example: true },
      { args: [[], [0]], expected: [0], example: true },
      { args: [[5], [1, 2, 3]], expected: [1, 2, 3, 5] },
      { args: [[1, 3, 5, 7], [2, 4, 6, 8]], expected: [1, 2, 3, 4, 5, 6, 7, 8] },
      { args: [[-2, -1], [-3]], expected: [-3, -2, -1] },
    ],
  },
  {
    slug: "maximum-depth-of-binary-tree",
    title: "Maximum Depth of Binary Tree",
    difficulty: "Easy",
    topics: ["Trees"],
    summary: "Measure how many levels deep a binary tree goes.",
    description: [
      "Given the `root` of a binary tree, return its maximum depth: the number of nodes along the longest path from the root down to a leaf.",
      "Trees are written level by level, with `null` for a missing child. `[3, 9, 20, null, null, 15, 7]` is a root `3` with children `9` and `20`, where `20` has children `15` and `7`.",
    ],
    constraints: ["The tree has between `0` and `10^4` nodes.", "`-100 <= Node.val <= 100`"],
    hint: "The depth of a tree is 1 plus the larger depth of its two subtrees. An empty tree has depth 0.",
    functionName: { js: "maxDepth", py: "max_depth" },
    params: [{ name: "root", type: "tree" }],
    returns: "int",
    tests: [
      { args: [[3, 9, 20, null, null, 15, 7]], expected: 3, example: true },
      { args: [[1, null, 2]], expected: 2, example: true },
      { args: [[]], expected: 0, example: true },
      { args: [[0]], expected: 1 },
      { args: [[1, 2, 3, 4, null, null, 5, 6]], expected: 4 },
      { args: [[1, 2, null, 3, null, 4, null, 5]], expected: 5 },
    ],
  },
  {
    slug: "invert-binary-tree",
    title: "Invert Binary Tree",
    difficulty: "Easy",
    topics: ["Trees"],
    summary: "Mirror a binary tree from left to right.",
    description: [
      "Given the `root` of a binary tree, swap the left and right children of every node, and return the root.",
      "Trees are written level by level, with `null` for a missing child.",
    ],
    constraints: ["The tree has between `0` and `100` nodes.", "`-100 <= Node.val <= 100`"],
    hint: "Swap the root's two children, then invert each subtree the same way. Recursion or a queue both work.",
    functionName: { js: "invertTree", py: "invert_tree" },
    params: [{ name: "root", type: "tree" }],
    returns: "tree",
    tests: [
      { args: [[4, 2, 7, 1, 3, 6, 9]], expected: [4, 7, 2, 9, 6, 3, 1], example: true },
      { args: [[2, 1, 3]], expected: [2, 3, 1], example: true },
      { args: [[]], expected: [], example: true },
      { args: [[1, 2]], expected: [1, null, 2] },
      { args: [[1, null, 2, 3]], expected: [1, 2, null, null, 3] },
      { args: [[5, 3, 8, 1, 4, 7, 9]], expected: [5, 8, 3, 9, 7, 4, 1] },
    ],
  },
];