import type { Problem } from "@/lib/problems";

// The second set of Easy problems.
export const EASY_PROBLEMS_2: Problem[] = [
  {
    slug: "contains-duplicate",
    title: "Contains Duplicate",
    difficulty: "Easy",
    topics: ["Arrays", "Hash map"],
    summary: "Check whether any number appears more than once.",
    description: [
      "Given an integer array `nums`, return `true` if any value appears at least twice, and `false` if every element is distinct.",
    ],
    constraints: ["`1 <= nums.length <= 10^5`", "`-10^9 <= nums[i] <= 10^9`"],
    hint: "Keep a set of the numbers you've seen. The first number that's already in the set is a duplicate.",
    functionName: { js: "containsDuplicate", py: "contains_duplicate" },
    params: [{ name: "nums", type: "int[]" }],
    returns: "bool",
    tests: [
      { args: [[1, 2, 3, 1]], expected: true, example: true, explanation: "The value 1 appears at indices 0 and 3." },
      { args: [[1, 2, 3, 4]], expected: false, example: true },
      { args: [[1, 1, 1, 3, 3, 4, 3, 2, 4, 2]], expected: true, example: true },
      { args: [[7]], expected: false },
      { args: [[-1, -1]], expected: true },
      { args: [[0, 5, -5, 10, 20]], expected: false },
    ],
  },
  {
    slug: "plus-one",
    title: "Plus One",
    difficulty: "Easy",
    topics: ["Arrays", "Math"],
    summary: "Add one to a number stored as an array of digits.",
    description: [
      "A large integer is stored as an array `digits`, most significant digit first, with no leading zeros (except for the number `0` itself).",
      "Add one to the integer and return the resulting array of digits.",
    ],
    constraints: ["`1 <= digits.length <= 100`", "`0 <= digits[i] <= 9`"],
    hint: "Walk from the last digit. A 9 becomes 0 and carries one to the left; any other digit just goes up by one and you're done. If every digit was 9, put a 1 in front.",
    functionName: { js: "plusOne", py: "plus_one" },
    params: [{ name: "digits", type: "int[]" }],
    returns: "int[]",
    tests: [
      { args: [[1, 2, 3]], expected: [1, 2, 4], example: true, explanation: "123 + 1 = 124." },
      { args: [[4, 3, 2, 1]], expected: [4, 3, 2, 2], example: true },
      { args: [[9]], expected: [1, 0], example: true, explanation: "9 + 1 = 10." },
      { args: [[9, 9, 9]], expected: [1, 0, 0, 0] },
      { args: [[0]], expected: [1] },
      { args: [[1, 9, 9]], expected: [2, 0, 0] },
    ],
  },
  {
    slug: "merge-sorted-array",
    title: "Merge Sorted Array",
    difficulty: "Easy",
    topics: ["Arrays", "Two pointers", "Sorting"],
    summary: "Merge one sorted array into another, in place.",
    description: [
      "You're given two sorted arrays, `nums1` and `nums2`, and two numbers: `m`, how many real values are in `nums1`, and `n`, the length of `nums2`. `nums1` has room for both: its last `n` slots are zeros waiting to be filled.",
      "Merge `nums2` into `nums1` **in place**, so that `nums1` ends up as one sorted array. The tests check `nums1` after your function finishes.",
    ],
    constraints: [
      "`nums1.length == m + n`",
      "`nums2.length == n`",
      "`0 <= m, n <= 200`",
      "`-10^9 <= nums1[i], nums2[j] <= 10^9`",
    ],
    hint: "Fill `nums1` from the back. Compare the largest remaining values of the two arrays and write the bigger one into the last free slot, so you never overwrite a value you still need.",
    functionName: { js: "mergeSortedArray", py: "merge_sorted_array" },
    params: [
      { name: "nums1", type: "int[]" },
      { name: "m", type: "int" },
      { name: "nums2", type: "int[]" },
      { name: "n", type: "int" },
    ],
    returns: "void",
    outputArg: 0,
    tests: [
      { args: [[1, 2, 3, 0, 0, 0], 3, [2, 5, 6], 3], expected: [1, 2, 2, 3, 5, 6], example: true },
      { args: [[1], 1, [], 0], expected: [1], example: true, explanation: "There's nothing to merge." },
      {
        args: [[0], 0, [1], 1],
        expected: [1],
        example: true,
        explanation: "nums1 has no real values yet, so it ends up holding nums2.",
      },
      { args: [[4, 5, 6, 0, 0, 0], 3, [1, 2, 3], 3], expected: [1, 2, 3, 4, 5, 6] },
      { args: [[2, 0], 1, [1], 1], expected: [1, 2] },
      { args: [[-1, 0, 0, 3, 3, 3, 0, 0, 0], 6, [1, 2, 2], 3], expected: [-1, 0, 0, 1, 2, 2, 3, 3, 3] },
    ],
  },
  {
    slug: "majority-element",
    title: "Majority Element",
    difficulty: "Easy",
    topics: ["Arrays", "Hash map"],
    summary: "Find the value that fills more than half the array.",
    description: [
      "Given an array `nums` of size `n`, return the majority element: the value that appears more than `n / 2` times. The array always has one.",
      "Can you do it in `O(n)` time and `O(1)` extra space?",
    ],
    constraints: ["`1 <= nums.length <= 5 * 10^4`", "`-10^9 <= nums[i] <= 10^9`"],
    hint: "Boyer–Moore voting: keep a candidate and a counter. Matching values add one, others subtract one, and when the counter hits zero the next value becomes the candidate. The majority always survives.",
    functionName: { js: "majorityElement", py: "majority_element" },
    params: [{ name: "nums", type: "int[]" }],
    returns: "int",
    tests: [
      { args: [[3, 2, 3]], expected: 3, example: true },
      { args: [[2, 2, 1, 1, 1, 2, 2]], expected: 2, example: true },
      { args: [[1]], expected: 1 },
      { args: [[6, 5, 5]], expected: 5 },
      { args: [[4, 4, 4, 7, 7]], expected: 4 },
      { args: [[-1, -1, 2]], expected: -1 },
    ],
  },
  {
    slug: "longest-common-prefix",
    title: "Longest Common Prefix",
    difficulty: "Easy",
    topics: ["Strings"],
    summary: "Find the longest start that every word shares.",
    description: [
      "Given an array of strings `strs`, return the longest string that is a prefix of every one of them. If they don't share a prefix, return an empty string.",
    ],
    constraints: [
      "`1 <= strs.length <= 200`",
      "`0 <= strs[i].length <= 200`",
      "Strings contain only lowercase English letters.",
    ],
    hint: "Compare the words one column at a time: check the first letter of every word, then the second, and stop at the first column where a word ends or disagrees.",
    functionName: { js: "longestCommonPrefix", py: "longest_common_prefix" },
    params: [{ name: "strs", type: "str[]" }],
    returns: "str",
    tests: [
      { args: [["flower", "flow", "flight"]], expected: "fl", example: true },
      {
        args: [["dog", "racecar", "car"]],
        expected: "",
        example: true,
        explanation: "The words don't share a first letter.",
      },
      { args: [["interview"]], expected: "interview" },
      { args: [["ab", "a"]], expected: "a" },
      { args: [["same", "same", "same"]], expected: "same" },
      { args: [["", "b"]], expected: "" },
    ],
  },
  {
    slug: "fizz-buzz",
    title: "Fizz Buzz",
    difficulty: "Easy",
    topics: ["Math", "Strings"],
    summary: "The classic: Fizz for threes, Buzz for fives, FizzBuzz for both.",
    description: [
      "Given an integer `n`, return an array with one string for each number from `1` to `n`:",
      "`FizzBuzz` if the number is divisible by both 3 and 5, `Fizz` if it's divisible by 3, `Buzz` if it's divisible by 5, and otherwise the number itself, written as a string.",
    ],
    constraints: ["`1 <= n <= 10^4`"],
    hint: "Check divisibility by 15 first (both 3 and 5), then by 3, then by 5.",
    functionName: { js: "fizzBuzz", py: "fizz_buzz" },
    params: [{ name: "n", type: "int" }],
    returns: "str[]",
    tests: [
      { args: [3], expected: ["1", "2", "Fizz"], example: true },
      { args: [5], expected: ["1", "2", "Fizz", "4", "Buzz"], example: true },
      {
        args: [15],
        expected: [
          "1",
          "2",
          "Fizz",
          "4",
          "Buzz",
          "Fizz",
          "7",
          "8",
          "Fizz",
          "Buzz",
          "11",
          "Fizz",
          "13",
          "14",
          "FizzBuzz",
        ],
        example: true,
      },
      { args: [1], expected: ["1"] },
      { args: [10], expected: ["1", "2", "Fizz", "4", "Buzz", "Fizz", "7", "8", "Fizz", "Buzz"] },
    ],
  },
  {
    slug: "palindrome-number",
    title: "Palindrome Number",
    difficulty: "Easy",
    topics: ["Math"],
    summary: "Check whether a number reads the same backward.",
    description: [
      "Given an integer `x`, return `true` if it reads the same forward and backward, and `false` otherwise.",
      "Negative numbers are never palindromes: `-121` reads as `121-` backward. Can you solve it without turning the number into a string?",
    ],
    constraints: ["`-2^31 <= x <= 2^31 - 1`"],
    hint: "Build the reverse of the number digit by digit (`reversed = reversed * 10 + x % 10`), then compare it with the original.",
    functionName: { js: "isPalindromeNumber", py: "is_palindrome_number" },
    params: [{ name: "x", type: "int" }],
    returns: "bool",
    tests: [
      { args: [121], expected: true, example: true },
      { args: [-121], expected: false, example: true, explanation: "Backward it reads 121-, which isn't the same." },
      { args: [10], expected: false, example: true, explanation: "Backward it reads 01." },
      { args: [0], expected: true },
      { args: [1221], expected: true },
      { args: [123], expected: false },
    ],
  },
  {
    slug: "reverse-string",
    title: "Reverse String",
    difficulty: "Easy",
    topics: ["Strings", "Two pointers"],
    summary: "Reverse an array of characters in place.",
    description: [
      "The string is given as an array of characters `s`. Reverse it **in place**, using only `O(1)` extra memory. The tests check `s` after your function finishes.",
    ],
    constraints: ["`1 <= s.length <= 10^5`", "Each `s[i]` is a printable ASCII character."],
    hint: "Swap the first and last characters, then move both pointers inward until they meet.",
    functionName: { js: "reverseString", py: "reverse_string" },
    params: [{ name: "s", type: "str[]" }],
    returns: "void",
    outputArg: 0,
    tests: [
      { args: [["h", "e", "l", "l", "o"]], expected: ["o", "l", "l", "e", "h"], example: true },
      { args: [["H", "a", "n", "n", "a", "h"]], expected: ["h", "a", "n", "n", "a", "H"], example: true },
      { args: [["a"]], expected: ["a"] },
      { args: [["a", "b"]], expected: ["b", "a"] },
      { args: [["1", "2", "3"]], expected: ["3", "2", "1"] },
    ],
  },
  {
    slug: "pascals-triangle",
    title: "Pascal's Triangle",
    difficulty: "Easy",
    topics: ["Arrays", "Dynamic programming"],
    summary: "Build the first rows of Pascal's triangle.",
    description: [
      "Given an integer `numRows`, return the first `numRows` rows of Pascal's triangle.",
      "Each row starts and ends with `1`, and every other number is the sum of the two numbers directly above it.",
    ],
    constraints: ["`1 <= numRows <= 30`"],
    hint: "Build each row from the previous one: `row[j] = prev[j - 1] + prev[j]`, with a `1` at both ends.",
    functionName: { js: "generate", py: "generate" },
    params: [{ name: "numRows", type: "int" }],
    returns: "int[][]",
    tests: [
      { args: [5], expected: [[1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 4, 6, 4, 1]], example: true },
      { args: [1], expected: [[1]], example: true },
      { args: [2], expected: [[1], [1, 1]] },
      { args: [6], expected: [[1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 4, 6, 4, 1], [1, 5, 10, 10, 5, 1]] },
    ],
  },
  {
    slug: "is-subsequence",
    title: "Is Subsequence",
    difficulty: "Easy",
    topics: ["Strings", "Two pointers"],
    summary: "Check whether one string's letters appear, in order, inside another.",
    description: [
      "Given two strings `s` and `t`, return `true` if `s` is a subsequence of `t`: if you can get `s` by deleting some (or none) of the characters of `t` without changing the order of the rest.",
    ],
    constraints: [
      "`0 <= s.length <= 100`",
      "`0 <= t.length <= 10^4`",
      "Both strings contain only lowercase English letters.",
    ],
    hint: "Walk through `t` with one pointer, and advance a second pointer in `s` each time the letters match. `s` is a subsequence if that pointer reaches its end.",
    functionName: { js: "isSubsequence", py: "is_subsequence" },
    params: [
      { name: "s", type: "str" },
      { name: "t", type: "str" },
    ],
    returns: "bool",
    tests: [
      { args: ["abc", "ahbgdc"], expected: true, example: true },
      { args: ["axc", "ahbgdc"], expected: false, example: true, explanation: "There's no x in t." },
      { args: ["", "abc"], expected: true },
      { args: ["abc", ""], expected: false },
      { args: ["aaa", "aa"], expected: false },
      { args: ["ace", "abcde"], expected: true },
    ],
  },
  {
    slug: "ransom-note",
    title: "Ransom Note",
    difficulty: "Easy",
    topics: ["Strings", "Hash map"],
    summary: "Check whether one string can be built from another's letters.",
    description: [
      "Given two strings `ransomNote` and `magazine`, return `true` if `ransomNote` can be built from the letters of `magazine`, and `false` otherwise.",
      "Each letter in `magazine` can be used only once.",
    ],
    constraints: [
      "`1 <= ransomNote.length, magazine.length <= 10^5`",
      "Both strings contain only lowercase English letters.",
    ],
    hint: "Count the letters in `magazine`, then spend them on `ransomNote`. If any count drops below zero, a letter is missing.",
    functionName: { js: "canConstruct", py: "can_construct" },
    params: [
      { name: "ransomNote", type: "str" },
      { name: "magazine", type: "str" },
    ],
    returns: "bool",
    tests: [
      { args: ["a", "b"], expected: false, example: true },
      { args: ["aa", "ab"], expected: false, example: true, explanation: "The magazine has only one a." },
      { args: ["aa", "aab"], expected: true, example: true },
      { args: ["abc", "cbaxyz"], expected: true },
      { args: ["zz", "z"], expected: false },
      { args: ["hello", "ohlleh"], expected: true },
    ],
  },
  {
    slug: "squares-of-a-sorted-array",
    title: "Squares of a Sorted Array",
    difficulty: "Easy",
    topics: ["Arrays", "Two pointers", "Sorting"],
    summary: "Square every number of a sorted array and keep it sorted.",
    description: [
      "Given an integer array `nums` sorted in non-decreasing order, return an array of the squares of each number, also sorted in non-decreasing order.",
      "Squaring and then sorting takes `O(n log n)`. Can you do it in `O(n)`?",
    ],
    constraints: [
      "`1 <= nums.length <= 10^4`",
      "`-10^4 <= nums[i] <= 10^4`",
      "`nums` is sorted in non-decreasing order.",
    ],
    hint: "The largest square is at one of the two ends. Compare the ends with two pointers and fill the answer from the back.",
    functionName: { js: "sortedSquares", py: "sorted_squares" },
    params: [{ name: "nums", type: "int[]" }],
    returns: "int[]",
    tests: [
      { args: [[-4, -1, 0, 3, 10]], expected: [0, 1, 9, 16, 100], example: true },
      { args: [[-7, -3, 2, 3, 11]], expected: [4, 9, 9, 49, 121], example: true },
      { args: [[1]], expected: [1] },
      { args: [[-5, -3, -2]], expected: [4, 9, 25] },
      { args: [[0, 0]], expected: [0, 0] },
    ],
  },
  {
    slug: "middle-of-the-linked-list",
    title: "Middle of the Linked List",
    difficulty: "Easy",
    topics: ["Linked list", "Two pointers"],
    summary: "Return the middle node of a linked list.",
    description: [
      "Given the `head` of a singly linked list, return its middle node. If there are two middle nodes, return the second one.",
      "Lists are written as arrays in the examples, and the tests read the list from the node you return: `[3, 4, 5]` means you returned the node holding `3`.",
    ],
    constraints: ["The list has between `1` and `100` nodes.", "`1 <= Node.val <= 100`"],
    hint: "Move a slow pointer one step and a fast pointer two steps at a time. When the fast pointer runs off the end, the slow one is in the middle.",
    functionName: { js: "middleNode", py: "middle_node" },
    params: [{ name: "head", type: "list" }],
    returns: "list",
    tests: [
      { args: [[1, 2, 3, 4, 5]], expected: [3, 4, 5], example: true, explanation: "The middle node holds 3." },
      {
        args: [[1, 2, 3, 4, 5, 6]],
        expected: [4, 5, 6],
        example: true,
        explanation: "There are two middle nodes, 3 and 4, so the answer is the second: 4.",
      },
      { args: [[1]], expected: [1] },
      { args: [[1, 2]], expected: [2] },
      { args: [[7, 8, 9]], expected: [8, 9] },
    ],
  },
  {
    slug: "same-tree",
    title: "Same Tree",
    difficulty: "Easy",
    topics: ["Trees"],
    summary: "Check whether two binary trees are identical.",
    description: [
      "Given the roots of two binary trees `p` and `q`, return `true` if they are the same tree: the same shape, with the same value in every node.",
      "Trees are written level by level, with `null` for a missing child.",
    ],
    constraints: ["Each tree has between `0` and `100` nodes.", "`-10^4 <= Node.val <= 10^4`"],
    hint: "Two trees are the same when both are empty, or when their roots match and their left subtrees and right subtrees are each the same.",
    functionName: { js: "isSameTree", py: "is_same_tree" },
    params: [
      { name: "p", type: "tree" },
      { name: "q", type: "tree" },
    ],
    returns: "bool",
    tests: [
      {
        args: [
          [1, 2, 3],
          [1, 2, 3],
        ],
        expected: true,
        example: true,
      },
      {
        args: [
          [1, 2],
          [1, null, 2],
        ],
        expected: false,
        example: true,
        explanation: "The 2 is a left child in one tree and a right child in the other.",
      },
      {
        args: [
          [1, 2, 1],
          [1, 1, 2],
        ],
        expected: false,
        example: true,
      },
      { args: [[], []], expected: true },
      { args: [[1], []], expected: false },
      {
        args: [
          [5, 3, 8, 1],
          [5, 3, 8, 1],
        ],
        expected: true,
      },
    ],
  },
  {
    slug: "symmetric-tree",
    title: "Symmetric Tree",
    difficulty: "Easy",
    topics: ["Trees", "Queue"],
    summary: "Check whether a binary tree is a mirror of itself.",
    description: [
      "Given the `root` of a binary tree, return `true` if it's symmetric around its center: its left half is a mirror image of its right half.",
      "Trees are written level by level, with `null` for a missing child.",
    ],
    constraints: ["The tree has between `1` and `1000` nodes.", "`-100 <= Node.val <= 100`"],
    hint: "Compare two subtrees at a time: they mirror each other when their roots match, the first one's left mirrors the second one's right, and the first one's right mirrors the second one's left.",
    functionName: { js: "isSymmetric", py: "is_symmetric" },
    params: [{ name: "root", type: "tree" }],
    returns: "bool",
    tests: [
      { args: [[1, 2, 2, 3, 4, 4, 3]], expected: true, example: true },
      { args: [[1, 2, 2, null, 3, null, 3]], expected: false, example: true },
      { args: [[1]], expected: true },
      { args: [[1, 2, 3]], expected: false },
      { args: [[2, 3, 3, 4, 5, 5, 4, null, null, 8, 9, 9, 8]], expected: true },
    ],
  },
  {
    slug: "diameter-of-binary-tree",
    title: "Diameter of Binary Tree",
    difficulty: "Easy",
    topics: ["Trees"],
    summary: "Find the longest path between any two nodes of a tree.",
    description: [
      "Given the `root` of a binary tree, return the length of its diameter: the number of edges on the longest path between any two nodes. The path doesn't have to pass through the root.",
      "Trees are written level by level, with `null` for a missing child.",
    ],
    constraints: ["The tree has between `1` and `10^4` nodes.", "`-100 <= Node.val <= 100`"],
    hint: "The longest path through a node is its left height plus its right height. Compute heights in one recursive pass, and keep the best sum you see along the way.",
    functionName: { js: "diameterOfBinaryTree", py: "diameter_of_binary_tree" },
    params: [{ name: "root", type: "tree" }],
    returns: "int",
    tests: [
      {
        args: [[1, 2, 3, 4, 5]],
        expected: 3,
        example: true,
        explanation: "The path 4 → 2 → 1 → 3 (or 5 → 2 → 1 → 3) has 3 edges.",
      },
      { args: [[1, 2]], expected: 1, example: true },
      { args: [[1]], expected: 0 },
      { args: [[1, 2, null, 3, null, 4, null, 5]], expected: 4 },
      { args: [[1, 2, 3, 4, 5, null, null, 6, null, null, 7]], expected: 4 },
    ],
  },
  {
    slug: "balanced-binary-tree",
    title: "Balanced Binary Tree",
    difficulty: "Easy",
    topics: ["Trees"],
    summary: "Check that no node's subtrees differ in height by more than one.",
    description: [
      "Given the `root` of a binary tree, return `true` if it's height-balanced: for every node, the heights of its left and right subtrees differ by at most one.",
      "Trees are written level by level, with `null` for a missing child.",
    ],
    constraints: ["The tree has between `0` and `5000` nodes.", "`-10^4 <= Node.val <= 10^4`"],
    hint: "Compute each subtree's height bottom-up, and return a special value (like `-1`) as soon as any subtree is unbalanced, so you only walk the tree once.",
    functionName: { js: "isBalanced", py: "is_balanced" },
    params: [{ name: "root", type: "tree" }],
    returns: "bool",
    tests: [
      { args: [[3, 9, 20, null, null, 15, 7]], expected: true, example: true },
      {
        args: [[1, 2, 2, 3, 3, null, null, 4, 4]],
        expected: false,
        example: true,
        explanation: "The root's left subtree has height 3 and its right subtree height 1.",
      },
      { args: [[]], expected: true, example: true },
      { args: [[1, 2, 3, 4]], expected: true },
      { args: [[1, 2, null, 3]], expected: false },
    ],
  },
  {
    slug: "search-insert-position",
    title: "Search Insert Position",
    difficulty: "Easy",
    topics: ["Arrays", "Binary search"],
    summary: "Find where a value is, or where it would go, in a sorted array.",
    description: [
      "Given a sorted array of distinct integers `nums` and a `target`, return the index of `target` if it's there. If it isn't, return the index where it would be inserted to keep the array sorted.",
      "Aim for `O(log n)` time.",
    ],
    constraints: [
      "`1 <= nums.length <= 10^4`",
      "`-10^4 <= nums[i], target <= 10^4`",
      "`nums` has distinct values, sorted in ascending order.",
    ],
    hint: "Binary search for the first index whose value is at least `target`. When the loop ends, the low pointer is the answer either way.",
    functionName: { js: "searchInsert", py: "search_insert" },
    params: [
      { name: "nums", type: "int[]" },
      { name: "target", type: "int" },
    ],
    returns: "int",
    tests: [
      { args: [[1, 3, 5, 6], 5], expected: 2, example: true },
      {
        args: [[1, 3, 5, 6], 2],
        expected: 1,
        example: true,
        explanation: "2 isn't there; it would go between 1 and 3.",
      },
      { args: [[1, 3, 5, 6], 7], expected: 4, example: true },
      { args: [[1, 3, 5, 6], 0], expected: 0 },
      { args: [[1], 1], expected: 0 },
      { args: [[2, 4, 6, 8, 10], 9], expected: 4 },
    ],
  },
];