import type { Problem } from "@/lib/problems";

// The second set of Hard problems.
export const HARD_PROBLEMS_2: Problem[] = [
  {
    slug: "first-missing-positive",
    title: "First Missing Positive",
    difficulty: "Hard",
    topics: ["Arrays", "Hash map"],
    summary: "Find the smallest positive integer that's not in the array.",
    description: [
      "Given an unsorted integer array `nums`, return the smallest positive integer that doesn't appear in it.",
      "The catch: do it in `O(n)` time using only `O(1)` extra space.",
    ],
    constraints: ["`1 <= nums.length <= 10^5`", "`-2^31 <= nums[i] <= 2^31 - 1`"],
    hint: "The answer is between `1` and `n + 1`. Use the array itself as the hash table: swap each value `v` in that range to index `v - 1`. Then the first index `i` that doesn't hold `i + 1` gives the answer.",
    functionName: { js: "firstMissingPositive", py: "first_missing_positive" },
    params: [{ name: "nums", type: "int[]" }],
    returns: "int",
    tests: [
      { args: [[1, 2, 0]], expected: 3, example: true },
      { args: [[3, 4, -1, 1]], expected: 2, example: true },
      { args: [[7, 8, 9, 11, 12]], expected: 1, example: true, explanation: "1 is already missing." },
      { args: [[1]], expected: 2 },
      { args: [[1, 1]], expected: 2 },
      { args: [[2, 1]], expected: 3 },
    ],
  },
  {
    slug: "longest-valid-parentheses",
    title: "Longest Valid Parentheses",
    difficulty: "Hard",
    topics: ["Stack", "Dynamic programming", "Strings"],
    summary: "Find the longest well-formed run of parentheses.",
    description: [
      "Given a string containing just the characters `(` and `)`, return the length of its longest valid (well-formed) parentheses substring.",
    ],
    constraints: ["`0 <= s.length <= 3 * 10^4`", "Each character is `(` or `)`."],
    hint: "Keep a stack of indexes, starting with `-1` as a base. Push the index of each `(`. For a `)`, pop; if the stack is now empty, push the current index as the new base, otherwise the current run is `i - top`.",
    functionName: { js: "longestValidParentheses", py: "longest_valid_parentheses" },
    params: [{ name: "s", type: "str" }],
    returns: "int",
    tests: [
      { args: ["(()"], expected: 2, example: true, explanation: "The longest valid run is ()." },
      { args: [")()())"], expected: 4, example: true, explanation: "The longest valid run is ()()." },
      { args: [""], expected: 0, example: true },
      { args: ["()(())"], expected: 6 },
      { args: ["())(())"], expected: 4 },
      { args: ["(()(("], expected: 2 },
    ],
  },
  {
    slug: "burst-balloons",
    title: "Burst Balloons",
    difficulty: "Hard",
    topics: ["Dynamic programming"],
    summary: "Choose the order to burst balloons for the most coins.",
    description: [
      "You have `n` balloons in a row, each painted with a number `nums[i]`. Bursting balloon `i` earns `nums[i - 1] * nums[i] * nums[i + 1]` coins, using its current neighbors; a missing neighbor at either end counts as `1`. After a burst, its two neighbors become adjacent.",
      "Return the maximum number of coins you can collect by bursting all the balloons.",
    ],
    constraints: ["`1 <= nums.length <= 300`", "`0 <= nums[i] <= 100`"],
    hint: "Think about which balloon in a range bursts last: at that moment its neighbors are the range's boundaries. Pad the array with a 1 at each end, and let `best[l][r]` be the most coins from bursting everything strictly between `l` and `r`.",
    functionName: { js: "maxCoins", py: "max_coins" },
    params: [{ name: "nums", type: "int[]" }],
    returns: "int",
    tests: [
      {
        args: [[3, 1, 5, 8]],
        expected: 167,
        example: true,
        explanation: "Burst 1, then 5, then 3, then 8: 3·1·5 + 3·5·8 + 1·3·8 + 1·8·1 = 15 + 120 + 24 + 8 = 167.",
      },
      { args: [[1, 5]], expected: 10, example: true },
      { args: [[7]], expected: 7 },
      { args: [[2, 3, 4]], expected: 36 },
      { args: [[9, 76, 64, 21]], expected: 116718 },
    ],
  },
  {
    slug: "longest-increasing-path-in-a-matrix",
    title: "Longest Increasing Path in a Matrix",
    difficulty: "Hard",
    topics: ["Graphs", "Dynamic programming", "Matrix"],
    summary: "Find the longest strictly increasing walk through a grid.",
    description: [
      "Given an `m × n` integer matrix, return the length of the longest strictly increasing path in it.",
      "From each cell you can move up, down, left or right, but not diagonally or outside the matrix.",
    ],
    constraints: ["`1 <= m, n <= 200`", "`0 <= matrix[i][j] <= 2^31 - 1`"],
    hint: "Depth-first search with memoization: the longest path starting at a cell is one more than the longest path starting at any bigger neighbor. Each cell is solved once, so the whole thing is `O(m · n)`.",
    functionName: { js: "longestIncreasingPath", py: "longest_increasing_path" },
    params: [{ name: "matrix", type: "int[][]" }],
    returns: "int",
    tests: [
      {
        args: [
          [
            [9, 9, 4],
            [6, 6, 8],
            [2, 1, 1],
          ],
        ],
        expected: 4,
        example: true,
        explanation: "The longest increasing path is 1 → 2 → 6 → 9.",
      },
      {
        args: [
          [
            [3, 4, 5],
            [3, 2, 6],
            [2, 2, 1],
          ],
        ],
        expected: 4,
        example: true,
        explanation: "The longest increasing path is 3 → 4 → 5 → 6.",
      },
      { args: [[[1]]], expected: 1, example: true },
      { args: [[[1, 2]]], expected: 2 },
      {
        args: [
          [
            [7, 8, 9],
            [6, 1, 2],
            [5, 4, 3],
          ],
        ],
        expected: 9,
      },
    ],
  },
  {
    slug: "reverse-nodes-in-k-group",
    title: "Reverse Nodes in k-Group",
    difficulty: "Hard",
    topics: ["Linked list"],
    summary: "Reverse a linked list k nodes at a time.",
    description: [
      "Given the `head` of a linked list, reverse its nodes `k` at a time and return the new head. If the number of nodes isn't a multiple of `k`, the nodes left over at the end stay in their original order.",
      "Change the links between nodes, not the values inside them. Lists are written as arrays in the examples.",
    ],
    constraints: ["The list has `n` nodes, with `1 <= k <= n <= 5000`.", "`0 <= Node.val <= 1000`"],
    hint: "Check that `k` nodes remain, reverse exactly those `k` links, then connect the reversed group to the previous group's tail and carry on from the group's new tail.",
    functionName: { js: "reverseKGroup", py: "reverse_k_group" },
    params: [
      { name: "head", type: "list" },
      { name: "k", type: "int" },
    ],
    returns: "list",
    tests: [
      { args: [[1, 2, 3, 4, 5], 2], expected: [2, 1, 4, 3, 5], example: true },
      { args: [[1, 2, 3, 4, 5], 3], expected: [3, 2, 1, 4, 5], example: true },
      { args: [[1, 2, 3, 4, 5], 1], expected: [1, 2, 3, 4, 5] },
      { args: [[1, 2], 2], expected: [2, 1] },
      { args: [[1, 2, 3, 4, 5, 6], 3], expected: [3, 2, 1, 6, 5, 4] },
    ],
  },
  {
    slug: "candy",
    title: "Candy",
    difficulty: "Hard",
    topics: ["Greedy", "Arrays"],
    summary: "Give out the fewest candies so that higher ratings get more.",
    description: [
      "Children stand in a line, and `ratings[i]` is the rating of child `i`. Give them candies so that every child gets at least one, and a child with a higher rating than a neighbor gets more candies than that neighbor.",
      "Return the minimum number of candies you need.",
    ],
    constraints: ["`1 <= ratings.length <= 2 * 10^4`", "`0 <= ratings[i] <= 2 * 10^4`"],
    hint: "Two passes. Left to right, give each child one more than its left neighbor when it's rated higher. Right to left, raise each child to one more than its right neighbor when it's rated higher, keeping the larger count.",
    functionName: { js: "candy", py: "candy" },
    params: [{ name: "ratings", type: "int[]" }],
    returns: "int",
    tests: [
      { args: [[1, 0, 2]], expected: 5, example: true, explanation: "Give 2, 1 and 2 candies." },
      {
        args: [[1, 2, 2]],
        expected: 4,
        example: true,
        explanation: "Give 1, 2 and 1. The third child has the same rating as the second, so it can have fewer.",
      },
      { args: [[1]], expected: 1 },
      { args: [[1, 3, 2, 2, 1]], expected: 7 },
      { args: [[1, 2, 87, 87, 87, 2, 1]], expected: 13 },
    ],
  },
  {
    slug: "basic-calculator",
    title: "Basic Calculator",
    difficulty: "Hard",
    topics: ["Stack", "Math", "Strings"],
    summary: "Evaluate an expression with +, -, parentheses and spaces.",
    description: [
      "Given a string `s` holding a valid expression, evaluate it and return the result. It can contain non-negative integers, `+`, `-`, parentheses and spaces, and a `-` can also be unary, as in `-(2 + 3)`.",
      "Don't use a built-in function that evaluates strings as code, like `eval`.",
    ],
    constraints: [
      "`1 <= s.length <= 3 * 10^5`",
      "`s` contains digits, `+`, `-`, `(`, `)` and spaces, and is always a valid expression.",
      "Every number and every intermediate result fits in a 32-bit signed integer.",
    ],
    hint: "Scan once, keeping a running `result` and the current `sign`. At `(`, push the result and sign onto a stack and start fresh; at `)`, finish the inner result and combine it with what you popped.",
    functionName: { js: "calculate", py: "calculate" },
    params: [{ name: "s", type: "str" }],
    returns: "int",
    tests: [
      { args: ["1 + 1"], expected: 2, example: true },
      { args: [" 2-1 + 2 "], expected: 3, example: true },
      { args: ["(1+(4+5+2)-3)+(6+8)"], expected: 23, example: true },
      { args: ["-(2+3)"], expected: -5 },
      { args: ["1-(     -2)"], expected: 3 },
      { args: ["10 - (3 - (2 + 1))"], expected: 10 },
      { args: ["2147483647"], expected: 2147483647 },
    ],
  },
  {
    slug: "maximal-rectangle",
    title: "Maximal Rectangle",
    difficulty: "Hard",
    topics: ["Stack", "Dynamic programming", "Matrix"],
    summary: "Find the largest rectangle made only of 1s in a grid.",
    description: [
      "Given a `rows × cols` grid `matrix` filled with the characters `0` and `1`, return the area of the largest rectangle containing only `1`s.",
    ],
    constraints: ["`1 <= rows, cols <= 200`", "Each `matrix[i][j]` is `0` or `1`, as a one-character string."],
    hint: "Treat each row as the floor of a histogram, where each column's bar is the number of consecutive 1s ending at that row. The answer is the best largest-rectangle-in-histogram over all rows, and a monotonic stack solves each row in `O(cols)`.",
    functionName: { js: "maximalRectangle", py: "maximal_rectangle" },
    params: [{ name: "matrix", type: "str[][]" }],
    returns: "int",
    tests: [
      {
        args: [
          [
            ["1", "0", "1", "0", "0"],
            ["1", "0", "1", "1", "1"],
            ["1", "1", "1", "1", "1"],
            ["1", "0", "0", "1", "0"],
          ],
        ],
        expected: 6,
        example: true,
      },
      { args: [[["0"]]], expected: 0, example: true },
      { args: [[["1"]]], expected: 1, example: true },
      {
        args: [
          [
            ["1", "1"],
            ["1", "1"],
          ],
        ],
        expected: 4,
      },
      {
        args: [
          [
            ["0", "1"],
            ["1", "0"],
          ],
        ],
        expected: 1,
      },
    ],
  },
];