import type { Problem } from "@/lib/problems";

// The original Hard problems.
export const HARD_PROBLEMS: Problem[] = [
  {
    slug: "trapping-rain-water",
    title: "Trapping Rain Water",
    difficulty: "Hard",
    topics: ["Arrays", "Two pointers"],
    summary: "Measure how much rain an elevation map can hold.",
    description: [
      "Given `n` non-negative integers `height` describing an elevation map where every bar has width 1, compute how much water it can trap after it rains.",
    ],
    constraints: ["`1 <= height.length <= 2 * 10^4`", "`0 <= height[i] <= 10^5`"],
    hint: "The water above a bar is `min(tallest bar to its left, tallest bar to its right) - its own height`. Two pointers moving inward can track both maximums in one pass.",
    functionName: { js: "trap", py: "trap" },
    params: [{ name: "height", type: "int[]" }],
    returns: "int",
    tests: [
      { args: [[0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]], expected: 6, example: true },
      { args: [[4, 2, 0, 3, 2, 5]], expected: 9, example: true },
      { args: [[1]], expected: 0 },
      { args: [[2, 0, 2]], expected: 2 },
      { args: [[3, 0, 0, 2, 0, 4]], expected: 10 },
      { args: [[5, 4, 3, 2, 1]], expected: 0 },
      { args: [[0, 3, 0, 1, 0, 3]], expected: 8 },
    ],
  },
  {
    slug: "largest-rectangle-in-histogram",
    title: "Largest Rectangle in Histogram",
    difficulty: "Hard",
    topics: ["Arrays", "Stack"],
    summary: "Find the biggest rectangle that fits under a bar chart.",
    description: [
      "Given an array `heights` describing a histogram where every bar has width 1, return the area of the largest rectangle that fits entirely inside the histogram.",
    ],
    constraints: ["`1 <= heights.length <= 10^5`", "`0 <= heights[i] <= 10^4`"],
    hint: "Keep a stack of bars with increasing heights. When a shorter bar arrives, pop the taller bars; each popped bar's rectangle stretches from the new top of the stack to the current position.",
    functionName: { js: "largestRectangleArea", py: "largest_rectangle_area" },
    params: [{ name: "heights", type: "int[]" }],
    returns: "int",
    tests: [
      {
        args: [[2, 1, 5, 6, 2, 3]],
        expected: 10,
        example: true,
        explanation: "The bars of height 5 and 6 make a 2 × 5 rectangle.",
      },
      { args: [[2, 4]], expected: 4, example: true },
      { args: [[1]], expected: 1 },
      { args: [[2, 2, 2, 2]], expected: 8 },
      { args: [[6, 2, 5, 4, 5, 1, 6]], expected: 12 },
      { args: [[0, 9]], expected: 9 },
      { args: [[4, 2, 0, 3, 2, 5]], expected: 6 },
    ],
  },
  {
    slug: "sliding-window-maximum",
    title: "Sliding Window Maximum",
    difficulty: "Hard",
    topics: ["Sliding window", "Queue"],
    summary: "Report the largest number in every window of size k.",
    description: [
      "Given an integer array `nums` and a window size `k`, slide the window from the left end of the array to the right end, one position at a time.",
      "Return an array holding the maximum value inside the window at each position.",
    ],
    constraints: ["`1 <= nums.length <= 10^5`", "`-10^4 <= nums[i] <= 10^4`", "`1 <= k <= nums.length`"],
    hint: "Keep a double-ended queue of indices whose values are decreasing. Drop indices that leave the window from the front, and smaller values from the back before adding a new index.",
    functionName: { js: "maxSlidingWindow", py: "max_sliding_window" },
    params: [
      { name: "nums", type: "int[]" },
      { name: "k", type: "int" },
    ],
    returns: "int[]",
    tests: [
      { args: [[1, 3, -1, -3, 5, 3, 6, 7], 3], expected: [3, 3, 5, 5, 6, 7], example: true },
      { args: [[1], 1], expected: [1], example: true },
      { args: [[9, 8, 7, 6], 2], expected: [9, 8, 7] },
      { args: [[1, 2, 3, 4], 4], expected: [4] },
      { args: [[4, -2], 2], expected: [4] },
      { args: [[7, 2, 4], 1], expected: [7, 2, 4] },
    ],
  },
  {
    slug: "minimum-window-substring",
    title: "Minimum Window Substring",
    difficulty: "Hard",
    topics: ["Strings", "Sliding window", "Hash map"],
    summary: "Find the shortest stretch of text containing every required letter.",
    description: [
      "Given strings `s` and `t`, return the shortest substring of `s` that contains every character of `t`, including duplicates. If no such substring exists, return an empty string.",
      "When an answer exists, it is guaranteed to be unique.",
    ],
    constraints: ["`1 <= s.length, t.length <= 10^5`", "`s` and `t` contain uppercase and lowercase English letters."],
    hint: "Grow a window to the right until it contains everything in `t`, then shrink it from the left as far as it stays valid. Track the smallest valid window you see.",
    functionName: { js: "minWindow", py: "min_window" },
    params: [
      { name: "s", type: "str" },
      { name: "t", type: "str" },
    ],
    returns: "str",
    tests: [
      { args: ["ADOBECODEBANC", "ABC"], expected: "BANC", example: true },
      { args: ["a", "a"], expected: "a", example: true },
      { args: ["a", "aa"], expected: "", example: true, explanation: "t needs two a's, but s only has one." },
      { args: ["ab", "b"], expected: "b" },
      { args: ["aa", "aa"], expected: "aa" },
      { args: ["xyzabcxyz", "zax"], expected: "xyza" },
    ],
  },
  {
    slug: "median-of-two-sorted-arrays",
    title: "Median of Two Sorted Arrays",
    difficulty: "Hard",
    topics: ["Arrays", "Binary search"],
    summary: "Find the median of two sorted arrays combined.",
    description: [
      "Given two sorted arrays `nums1` and `nums2`, return the median of the two arrays combined.",
      "The median is the middle value of the combined sorted list, or the average of the two middle values when its length is even. Aim for `O(log (m + n))` time.",
    ],
    constraints: [
      "`0 <= nums1.length, nums2.length <= 1000`",
      "`1 <= nums1.length + nums2.length <= 2000`",
      "`-10^6 <= nums1[i], nums2[i] <= 10^6`",
    ],
    hint: "Binary search for a split of the shorter array such that everything left of the split in both arrays is no bigger than everything to the right.",
    functionName: { js: "findMedianSortedArrays", py: "find_median_sorted_arrays" },
    params: [
      { name: "nums1", type: "int[]" },
      { name: "nums2", type: "int[]" },
    ],
    returns: "float",
    tests: [
      { args: [[1, 3], [2]], expected: 2, example: true, explanation: "Combined, the array is [1, 2, 3], so the median is 2." },
      {
        args: [[1, 2], [3, 4]],
        expected: 2.5,
        example: true,
        explanation: "Combined, the array is [1, 2, 3, 4], so the median is (2 + 3) / 2 = 2.5.",
      },
      { args: [[], [1]], expected: 1 },
      { args: [[2], []], expected: 2 },
      { args: [[0, 0], [0, 0]], expected: 0 },
      { args: [[1, 5, 9], [2, 3, 10, 11]], expected: 5 },
      { args: [[-5, -3, -1], [-2, 4]], expected: -2 },
      { args: [[1, 2], [1, 2, 3]], expected: 2 },
    ],
  },
  {
    slug: "merge-k-sorted-lists",
    title: "Merge K Sorted Lists",
    difficulty: "Hard",
    topics: ["Linked list", "Heap"],
    summary: "Combine any number of sorted linked lists into one.",
    description: [
      "You're given an array of `k` linked lists, `lists`, each sorted in ascending order. Merge them all into one sorted linked list and return its head.",
      "Lists are written as arrays: `[[1, 4], [2]]` means two lists, `1 → 4` and `2`.",
    ],
    constraints: ["`0 <= k <= 10^4`", "Each list has between `0` and `500` nodes.", "`-10^4 <= Node.val <= 10^4`"],
    hint: "Keep a min-heap holding the current head of every list. Repeatedly pop the smallest node, append it, and push its successor. Merging the lists in pairs also works.",
    functionName: { js: "mergeKLists", py: "merge_k_lists" },
    params: [{ name: "lists", type: "list[]" }],
    returns: "list",
    tests: [
      {
        args: [
          [
            [1, 4, 5],
            [1, 3, 4],
            [2, 6],
          ],
        ],
        expected: [1, 1, 2, 3, 4, 4, 5, 6],
        example: true,
      },
      { args: [[]], expected: [], example: true },
      { args: [[[]]], expected: [], example: true },
      { args: [[[2], [1]]], expected: [1, 2] },
      { args: [[[1, 2, 3], [], [0, 10]]], expected: [0, 1, 2, 3, 10] },
      { args: [[[-5, 0, 5], [-6, 6], [-7, 7], [1]]], expected: [-7, -6, -5, 0, 1, 5, 6, 7] },
    ],
  },
  {
    slug: "binary-tree-maximum-path-sum",
    title: "Binary Tree Maximum Path Sum",
    difficulty: "Hard",
    topics: ["Trees", "Dynamic programming"],
    summary: "Find the path through a tree whose values add up to the most.",
    description: [
      "A path in a binary tree is a sequence of nodes where each pair of neighbours is joined by an edge. A node appears at most once in a path, and the path doesn't have to pass through the root.",
      "Given the `root` of a binary tree, return the largest sum of node values over any non-empty path.",
    ],
    constraints: ["The tree has between `1` and `3 * 10^4` nodes.", "`-1000 <= Node.val <= 1000`"],
    hint: "For each node, compute the best downward path starting there (dropping negative branches). The best path that bends at this node is its value plus the best left and right downward paths.",
    functionName: { js: "maxPathSum", py: "max_path_sum" },
    params: [{ name: "root", type: "tree" }],
    returns: "int",
    tests: [
      { args: [[1, 2, 3]], expected: 6, example: true, explanation: "The path 2 → 1 → 3 adds up to 6." },
      {
        args: [[-10, 9, 20, null, null, 15, 7]],
        expected: 42,
        example: true,
        explanation: "The path 15 → 20 → 7 adds up to 42.",
      },
      { args: [[-3]], expected: -3 },
      { args: [[2, -1]], expected: 2 },
      { args: [[-2, 1]], expected: 1 },
      { args: [[5, 4, 8, 11, null, 13, 4, 7, 2, null, null, null, 1]], expected: 48 },
    ],
  },
  {
    slug: "word-ladder",
    title: "Word Ladder",
    difficulty: "Hard",
    topics: ["Graphs", "Strings", "Queue"],
    summary: "Find the shortest chain of one-letter changes between two words.",
    description: [
      "A transformation sequence from `beginWord` to `endWord` changes one letter at a time, and every word after `beginWord` must appear in `wordList`.",
      "Return the number of words in the shortest such sequence, counting both `beginWord` and `endWord`, or `0` if no sequence exists.",
    ],
    constraints: [
      "`1 <= beginWord.length <= 10`",
      "All words have the same length and contain only lowercase English letters.",
      "`1 <= wordList.length <= 5000`",
      "`beginWord` and `endWord` are different.",
    ],
    hint: "Treat each word as a node connected to the words that differ from it by one letter. A breadth-first search from `beginWord` finds the shortest path.",
    functionName: { js: "ladderLength", py: "ladder_length" },
    params: [
      { name: "beginWord", type: "str" },
      { name: "endWord", type: "str" },
      { name: "wordList", type: "str[]" },
    ],
    returns: "int",
    tests: [
      {
        args: ["hit", "cog", ["hot", "dot", "dog", "lot", "log", "cog"]],
        expected: 5,
        example: true,
        explanation: "hit → hot → dot → dog → cog.",
      },
      {
        args: ["hit", "cog", ["hot", "dot", "dog", "lot", "log"]],
        expected: 0,
        example: true,
        explanation: "\"cog\" isn't in the word list, so it can't be reached.",
      },
      { args: ["a", "c", ["a", "b", "c"]], expected: 2 },
      { args: ["red", "tax", ["ted", "tex", "red", "tax", "tad", "den", "rex", "pee"]], expected: 4 },
      { args: ["cold", "warm", ["cord", "card", "ward", "warm", "wold", "word", "worm", "wore", "wire"]], expected: 5 },
    ],
  },
  {
    slug: "n-queens",
    title: "N-Queens",
    difficulty: "Hard",
    topics: ["Backtracking"],
    summary: "Count the ways to place n queens so that none attack each other.",
    description: [
      "Place `n` queens on an `n × n` chessboard so that no two queens attack each other: no two may share a row, a column or a diagonal.",
      "Given `n`, return the number of distinct ways to do it.",
    ],
    constraints: ["`1 <= n <= 9`"],
    hint: "Place one queen per row with backtracking. Track which columns and which diagonals (`row - col` and `row + col`) are taken, so every check takes constant time.",
    functionName: { js: "totalNQueens", py: "total_n_queens" },
    params: [{ name: "n", type: "int" }],
    returns: "int",
    tests: [
      { args: [4], expected: 2, example: true },
      { args: [1], expected: 1, example: true },
      { args: [2], expected: 0 },
      { args: [3], expected: 0 },
      { args: [5], expected: 10 },
      { args: [6], expected: 4 },
      { args: [8], expected: 92 },
    ],
  },
  {
    slug: "edit-distance",
    title: "Edit Distance",
    difficulty: "Hard",
    topics: ["Strings", "Dynamic programming"],
    summary: "Count the fewest edits that turn one word into another.",
    description: [
      "Given two strings `word1` and `word2`, return the minimum number of operations needed to turn `word1` into `word2`.",
      "Each operation inserts one character, deletes one character, or replaces one character.",
    ],
    constraints: ["`0 <= word1.length, word2.length <= 500`", "Both words contain only lowercase English letters."],
    hint: "Let `d[i][j]` be the distance between the first `i` letters of `word1` and the first `j` letters of `word2`. Each cell depends only on its left, upper and upper-left neighbours.",
    functionName: { js: "minDistance", py: "min_distance" },
    params: [
      { name: "word1", type: "str" },
      { name: "word2", type: "str" },
    ],
    returns: "int",
    tests: [
      {
        args: ["horse", "ros"],
        expected: 3,
        example: true,
        explanation: "horse → rorse (replace h) → rose (delete r) → ros (delete e).",
      },
      { args: ["intention", "execution"], expected: 5, example: true },
      { args: ["", "abc"], expected: 3 },
      { args: ["abc", "abc"], expected: 0 },
      { args: ["kitten", "sitting"], expected: 3 },
      { args: ["a", ""], expected: 1 },
      { args: ["sunday", "saturday"], expected: 3 },
    ],
  },
  {
    slug: "regular-expression-matching",
    title: "Regular Expression Matching",
    difficulty: "Hard",
    topics: ["Strings", "Dynamic programming"],
    summary: "Match a string against a pattern with . and * wildcards.",
    description: [
      "Implement pattern matching with two special characters: `.` matches any single character, and `*` matches zero or more copies of the element right before it.",
      "The match must cover the **entire** string `s`, not just part of it. Return `true` if `s` matches the pattern `p`.",
    ],
    constraints: [
      "`1 <= s.length, p.length <= 20`",
      "`s` contains only lowercase letters; `p` contains lowercase letters, `.` and `*`.",
      "Every `*` has a letter or `.` right before it.",
    ],
    hint: "Let `dp[i][j]` mean the first `i` characters of `s` match the first `j` characters of `p`. A `*` either matches zero copies (skip the pair) or one more copy, if its element matches the current character.",
    functionName: { js: "isMatch", py: "is_match" },
    params: [
      { name: "s", type: "str" },
      { name: "p", type: "str" },
    ],
    returns: "bool",
    tests: [
      {
        args: ["aa", "a"],
        expected: false,
        example: true,
        explanation: "\"a\" matches only one character, not the whole string.",
      },
      { args: ["aa", "a*"], expected: true, example: true },
      { args: ["ab", ".*"], expected: true, example: true, explanation: "\".*\" matches any sequence of characters." },
      { args: ["aab", "c*a*b"], expected: true },
      { args: ["mississippi", "mis*is*p*."], expected: false },
      { args: ["abc", "a.c"], expected: true },
      { args: ["abcd", "d*"], expected: false },
      { args: ["aaa", "a*a"], expected: true },
    ],
  },
];