import type { Problem } from "@/lib/problems";

// The original Medium problems.
export const MEDIUM_PROBLEMS: Problem[] = [
  {
    slug: "maximum-subarray",
    title: "Maximum Subarray",
    difficulty: "Medium",
    topics: ["Arrays", "Dynamic programming"],
    summary: "Find the contiguous run of numbers with the largest sum.",
    description: [
      "Given an integer array `nums`, find the contiguous subarray (containing at least one number) with the largest sum, and return that sum.",
    ],
    constraints: ["`1 <= nums.length <= 10^5`", "`-10^4 <= nums[i] <= 10^4`"],
    hint: "Walk through the array keeping the best sum of a subarray that ends at the current position. If that running sum goes negative, starting fresh is better.",
    functionName: { js: "maxSubArray", py: "max_sub_array" },
    params: [{ name: "nums", type: "int[]" }],
    returns: "int",
    tests: [
      {
        args: [[-2, 1, -3, 4, -1, 2, 1, -5, 4]],
        expected: 6,
        example: true,
        explanation: "The subarray [4, -1, 2, 1] has the largest sum, 6.",
      },
      { args: [[1]], expected: 1, example: true },
      { args: [[5, 4, -1, 7, 8]], expected: 23, example: true },
      { args: [[-3, -1, -2]], expected: -1 },
      { args: [[-2, -3, 4, -1, -2, 1, 5, -3]], expected: 7 },
      { args: [[0, 0, 0]], expected: 0 },
      { args: [[8, -19, 5, -4, 20]], expected: 21 },
    ],
  },
  {
    slug: "group-anagrams",
    title: "Group Anagrams",
    difficulty: "Medium",
    topics: ["Strings", "Hash map", "Sorting"],
    summary: "Group together words that are anagrams of each other.",
    description: [
      "Given an array of strings `words`, group the words that are anagrams of each other.",
      "You can return the groups in any order, and the words inside each group in any order.",
    ],
    constraints: ["`1 <= words.length <= 10^4`", "`0 <= words[i].length <= 100`", "Words contain only lowercase English letters."],
    hint: "Two words are anagrams exactly when their sorted letters match. Use the sorted word as a key in a hash map of groups.",
    functionName: { js: "groupAnagrams", py: "group_anagrams" },
    params: [{ name: "words", type: "str[]" }],
    returns: "str[][]",
    compare: "unordered-deep",
    tests: [
      {
        args: [["eat", "tea", "tan", "ate", "nat", "bat"]],
        expected: [["bat"], ["nat", "tan"], ["ate", "eat", "tea"]],
        example: true,
      },
      { args: [[""]], expected: [[""]], example: true },
      { args: [["a"]], expected: [["a"]], example: true },
      { args: [["abc", "bca", "cab", "xyz", "zyx", "q"]], expected: [["abc", "bca", "cab"], ["xyz", "zyx"], ["q"]] },
      { args: [["ab", "ba", "ab"]], expected: [["ab", "ba", "ab"]] },
    ],
  },
  {
    slug: "longest-substring-without-repeating-characters",
    title: "Longest Substring Without Repeats",
    difficulty: "Medium",
    topics: ["Strings", "Sliding window", "Hash map"],
    summary: "Find the longest stretch of text with no repeated character.",
    description: [
      "Given a string `s`, return the length of the longest substring that contains no repeated characters.",
      "A substring is a contiguous run of characters within the string.",
    ],
    constraints: ["`0 <= s.length <= 5 * 10^4`", "`s` may contain letters, digits, symbols and spaces."],
    hint: "Keep a window with no repeats. Extend it one character at a time, and when a character repeats, move the window's start past that character's previous position.",
    functionName: { js: "lengthOfLongestSubstring", py: "length_of_longest_substring" },
    params: [{ name: "s", type: "str" }],
    returns: "int",
    tests: [
      { args: ["abcabcbb"], expected: 3, example: true, explanation: "\"abc\" is the longest run without repeats." },
      { args: ["bbbbb"], expected: 1, example: true },
      { args: ["pwwkew"], expected: 3, example: true, explanation: "\"wke\" has length 3." },
      { args: [""], expected: 0 },
      { args: [" "], expected: 1 },
      { args: ["dvdf"], expected: 3 },
      { args: ["abba"], expected: 2 },
      { args: ["tmmzuxt"], expected: 5 },
    ],
  },
  {
    slug: "product-of-array-except-self",
    title: "Product Except Self",
    difficulty: "Medium",
    topics: ["Arrays", "Prefix sums"],
    summary: "Multiply everything except the current element, without division.",
    description: [
      "Given an integer array `nums`, return an array `answer` where `answer[i]` is the product of every element of `nums` except `nums[i]`.",
      "Solve it in `O(n)` time without using division.",
    ],
    constraints: ["`2 <= nums.length <= 10^5`", "`-30 <= nums[i] <= 30`", "Every product fits in a 32-bit integer."],
    hint: "`answer[i]` is (the product of everything to the left of `i`) times (the product of everything to the right). Build both in two passes.",
    functionName: { js: "productExceptSelf", py: "product_except_self" },
    params: [{ name: "nums", type: "int[]" }],
    returns: "int[]",
    tests: [
      { args: [[1, 2, 3, 4]], expected: [24, 12, 8, 6], example: true },
      { args: [[-1, 1, 0, -3, 3]], expected: [0, 0, 9, 0, 0], example: true },
      { args: [[2, 3]], expected: [3, 2] },
      { args: [[0, 0]], expected: [0, 0] },
      { args: [[5, 1, 1, 1]], expected: [1, 5, 5, 5] },
      { args: [[-2, -3, 4]], expected: [-12, -8, 6] },
    ],
  },
  {
    slug: "top-k-frequent-elements",
    title: "Top K Frequent Elements",
    difficulty: "Medium",
    topics: ["Hash map", "Heap", "Sorting"],
    summary: "Return the k numbers that appear most often.",
    description: [
      "Given an integer array `nums` and an integer `k`, return the `k` most frequent elements. You can return them in any order.",
      "The answer is guaranteed to be unique.",
    ],
    constraints: ["`1 <= nums.length <= 10^5`", "`1 <= k <=` the number of distinct values in `nums`"],
    hint: "Count each number's frequency. Then either sort the distinct numbers by count, or put them into buckets indexed by count.",
    functionName: { js: "topKFrequent", py: "top_k_frequent" },
    params: [
      { name: "nums", type: "int[]" },
      { name: "k", type: "int" },
    ],
    returns: "int[]",
    compare: "unordered",
    tests: [
      { args: [[1, 1, 1, 2, 2, 3], 2], expected: [1, 2], example: true },
      { args: [[1], 1], expected: [1], example: true },
      { args: [[4, 4, 4, 5, 5, 6, 6, 6, 6], 2], expected: [6, 4] },
      { args: [[-1, -1, 2, 2, 2, 3], 2], expected: [2, -1] },
      { args: [[7, 7, 8, 8, 8, 9, 9, 9, 9, 9], 3], expected: [9, 8, 7] },
    ],
  },
  {
    slug: "three-sum",
    title: "3Sum",
    difficulty: "Medium",
    topics: ["Arrays", "Two pointers", "Sorting"],
    summary: "Find every triplet of numbers that adds up to zero.",
    description: [
      "Given an integer array `nums`, return every unique triplet `[a, b, c]` of values taken from three different positions such that `a + b + c = 0`.",
      "The answer must not contain duplicate triplets. You can return the triplets in any order, and the numbers inside each triplet in any order.",
    ],
    constraints: ["`3 <= nums.length <= 3000`", "`-10^5 <= nums[i] <= 10^5`"],
    hint: "Sort the array. Fix the first number, then use two pointers on the rest to find pairs that sum to its negative. Skip repeated values to avoid duplicate triplets.",
    functionName: { js: "threeSum", py: "three_sum" },
    params: [{ name: "nums", type: "int[]" }],
    returns: "int[][]",
    compare: "unordered-deep",
    tests: [
      { args: [[-1, 0, 1, 2, -1, -4]], expected: [[-1, -1, 2], [-1, 0, 1]], example: true },
      { args: [[0, 1, 1]], expected: [], example: true, explanation: "No three numbers add up to 0." },
      { args: [[0, 0, 0]], expected: [[0, 0, 0]], example: true },
      { args: [[-2, 0, 1, 1, 2]], expected: [[-2, 0, 2], [-2, 1, 1]] },
      { args: [[1, 2, -2, -1]], expected: [] },
      { args: [[3, 0, -2, -1, 1, 2]], expected: [[-2, -1, 3], [-2, 0, 2], [-1, 0, 1]] },
      { args: [[-1, 0, 1, 0]], expected: [[-1, 0, 1]] },
    ],
  },
  {
    slug: "container-with-most-water",
    title: "Container With Most Water",
    difficulty: "Medium",
    topics: ["Arrays", "Two pointers", "Greedy"],
    summary: "Pick two walls that hold the most water between them.",
    description: [
      "You're given an array `height` where `height[i]` is the height of a vertical line at position `i`.",
      "Choose two lines that, together with the x-axis, form a container. It holds (the distance between the lines) × (the height of the shorter line) units of water. Return the most water a container can hold.",
    ],
    constraints: ["`2 <= height.length <= 10^5`", "`0 <= height[i] <= 10^4`"],
    hint: "Start with the widest container (both ends) and move the shorter wall inward. Moving the taller one can never help, because the shorter wall limits the height.",
    functionName: { js: "maxArea", py: "max_area" },
    params: [{ name: "height", type: "int[]" }],
    returns: "int",
    tests: [
      {
        args: [[1, 8, 6, 2, 5, 4, 8, 3, 7]],
        expected: 49,
        example: true,
        explanation: "The lines at positions 1 and 8 are 7 apart, and the shorter is 7 tall: 7 × 7 = 49.",
      },
      { args: [[1, 1]], expected: 1, example: true },
      { args: [[4, 3, 2, 1, 4]], expected: 16 },
      { args: [[1, 2, 1]], expected: 2 },
      { args: [[2, 3, 4, 5, 18, 17, 6]], expected: 17 },
      { args: [[0, 0, 0]], expected: 0 },
    ],
  },
  {
    slug: "longest-consecutive-sequence",
    title: "Longest Consecutive Sequence",
    difficulty: "Medium",
    topics: ["Arrays", "Hash map"],
    summary: "Find the longest run of consecutive integers, in any order.",
    description: [
      "Given an unsorted array of integers `nums`, return the length of the longest sequence of consecutive integers (like `4, 5, 6, 7`) whose values all appear in `nums`.",
      "Aim for `O(n)` time.",
    ],
    constraints: ["`0 <= nums.length <= 10^5`", "`-10^9 <= nums[i] <= 10^9`"],
    hint: "Put every number in a set. Only start counting from numbers `x` where `x - 1` is missing; those are the starts of runs.",
    functionName: { js: "longestConsecutive", py: "longest_consecutive" },
    params: [{ name: "nums", type: "int[]" }],
    returns: "int",
    tests: [
      { args: [[100, 4, 200, 1, 3, 2]], expected: 4, example: true, explanation: "The longest run is 1, 2, 3, 4." },
      { args: [[0, 3, 7, 2, 5, 8, 4, 6, 0, 1]], expected: 9, example: true },
      { args: [[]], expected: 0 },
      { args: [[1, 2, 0, 1]], expected: 3 },
      { args: [[9, 1, -3, 2, 4, 8, 3, -1, 6, -2, -4, 7]], expected: 4 },
      { args: [[5]], expected: 1 },
    ],
  },
  {
    slug: "subarray-sum-equals-k",
    title: "Subarray Sum Equals K",
    difficulty: "Medium",
    topics: ["Arrays", "Prefix sums", "Hash map"],
    summary: "Count the contiguous stretches that add up to k.",
    description: [
      "Given an integer array `nums` and an integer `k`, return the number of contiguous, non-empty subarrays whose sum equals `k`.",
    ],
    constraints: ["`1 <= nums.length <= 2 * 10^4`", "`-1000 <= nums[i] <= 1000`", "`-10^7 <= k <= 10^7`"],
    hint: "Keep a hash map counting the running prefix sums seen so far. A subarray ending here adds up to `k` whenever `prefix - k` appeared earlier.",
    functionName: { js: "subarraySum", py: "subarray_sum" },
    params: [
      { name: "nums", type: "int[]" },
      { name: "k", type: "int" },
    ],
    returns: "int",
    tests: [
      { args: [[1, 1, 1], 2], expected: 2, example: true },
      { args: [[1, 2, 3], 3], expected: 2, example: true, explanation: "[1, 2] and [3] both add up to 3." },
      { args: [[1], 0], expected: 0 },
      { args: [[1, -1, 0], 0], expected: 3 },
      { args: [[3, 4, 7, 2, -3, 1, 4, 2], 7], expected: 4 },
      { args: [[0, 0, 0], 0], expected: 6 },
    ],
  },
  {
    slug: "merge-intervals",
    title: "Merge Intervals",
    difficulty: "Medium",
    topics: ["Arrays", "Sorting", "Intervals"],
    summary: "Combine overlapping ranges into one sorted list.",
    description: [
      "Given an array of `intervals` where `intervals[i] = [start, end]`, merge every group of overlapping intervals and return the non-overlapping result, sorted by start.",
      "Intervals that touch at an endpoint, like `[1, 4]` and `[4, 5]`, count as overlapping.",
    ],
    constraints: ["`1 <= intervals.length <= 10^4`", "`0 <= start <= end <= 10^4`"],
    hint: "Sort the intervals by start. Then walk through them: each one either extends the last merged interval or starts a new one.",
    functionName: { js: "merge", py: "merge" },
    params: [{ name: "intervals", type: "int[][]" }],
    returns: "int[][]",
    tests: [
      {
        args: [[[1, 3], [2, 6], [8, 10], [15, 18]]],
        expected: [[1, 6], [8, 10], [15, 18]],
        example: true,
        explanation: "[1, 3] and [2, 6] overlap, so they merge into [1, 6].",
      },
      { args: [[[1, 4], [4, 5]]], expected: [[1, 5]], example: true },
      { args: [[[4, 7], [1, 4]]], expected: [[1, 7]], example: true },
      { args: [[[1, 4], [2, 3]]], expected: [[1, 4]] },
      { args: [[[1, 2]]], expected: [[1, 2]] },
      { args: [[[5, 6], [1, 2], [3, 4]]], expected: [[1, 2], [3, 4], [5, 6]] },
      { args: [[[1, 10], [2, 3], [4, 5], [11, 12]]], expected: [[1, 10], [11, 12]] },
    ],
  },
  {
    slug: "insert-interval",
    title: "Insert Interval",
    difficulty: "Medium",
    topics: ["Arrays", "Intervals"],
    summary: "Add a new range to a sorted list of ranges, merging where needed.",
    description: [
      "You're given an array of non-overlapping `intervals` sorted by start, where `intervals[i] = [start, end]`, and one more interval, `newInterval`.",
      "Insert `newInterval` so the list stays sorted and non-overlapping, merging intervals where necessary, and return the result. Intervals that touch at an endpoint count as overlapping.",
    ],
    constraints: [
      "`0 <= intervals.length <= 10^4`",
      "`0 <= start <= end <= 10^5`",
      "`intervals` is sorted by start and has no overlaps.",
    ],
    hint: "Copy the intervals that end before the new one starts, merge every interval that overlaps it into a single range, then copy the rest.",
    functionName: { js: "insert", py: "insert" },
    params: [
      { name: "intervals", type: "int[][]" },
      { name: "newInterval", type: "int[]" },
    ],
    returns: "int[][]",
    tests: [
      { args: [[[1, 3], [6, 9]], [2, 5]], expected: [[1, 5], [6, 9]], example: true },
      {
        args: [[[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]], [4, 8]],
        expected: [[1, 2], [3, 10], [12, 16]],
        example: true,
        explanation: "[4, 8] overlaps [3, 5], [6, 7] and [8, 10], so they merge into [3, 10].",
      },
      { args: [[], [5, 7]], expected: [[5, 7]], example: true },
      { args: [[[1, 5]], [2, 3]], expected: [[1, 5]] },
      { args: [[[1, 5]], [6, 8]], expected: [[1, 5], [6, 8]] },
      { args: [[[3, 5], [8, 10]], [1, 2]], expected: [[1, 2], [3, 5], [8, 10]] },
      { args: [[[1, 2], [5, 6]], [2, 5]], expected: [[1, 6]] },
    ],
  },
  {
    slug: "search-in-rotated-sorted-array",
    title: "Search in Rotated Sorted Array",
    difficulty: "Medium",
    topics: ["Arrays", "Binary search"],
    summary: "Binary search in a sorted array that has been rotated.",
    description: [
      "An array of distinct integers, sorted in ascending order, has been rotated at some unknown pivot. For example, `[0, 1, 2, 4, 5, 6, 7]` might become `[4, 5, 6, 7, 0, 1, 2]`.",
      "Given the rotated array `nums` and an integer `target`, return the index of `target`, or `-1` if it isn't in `nums`. Aim for `O(log n)` time.",
    ],
    constraints: ["`1 <= nums.length <= 5000`", "`-10^4 <= nums[i], target <= 10^4`", "All values in `nums` are distinct."],
    hint: "At every step of a binary search, at least one half of the range is sorted. Check whether `target` falls inside that sorted half to decide which half to keep.",
    functionName: { js: "searchRotated", py: "search_rotated" },
    params: [
      { name: "nums", type: "int[]" },
      { name: "target", type: "int" },
    ],
    returns: "int",
    tests: [
      { args: [[4, 5, 6, 7, 0, 1, 2], 0], expected: 4, example: true },
      { args: [[4, 5, 6, 7, 0, 1, 2], 3], expected: -1, example: true },
      { args: [[1], 0], expected: -1, example: true },
      { args: [[1], 1], expected: 0 },
      { args: [[3, 1], 1], expected: 1 },
      { args: [[5, 1, 3], 5], expected: 0 },
      { args: [[6, 7, 8, 1, 2, 3, 4, 5], 8], expected: 2 },
      { args: [[6, 7, 8, 1, 2, 3, 4, 5], 4], expected: 6 },
    ],
  },
  {
    slug: "daily-temperatures",
    title: "Daily Temperatures",
    difficulty: "Medium",
    topics: ["Arrays", "Stack"],
    summary: "For each day, count how long until a warmer day arrives.",
    description: [
      "Given an array `temperatures` of daily temperatures, return an array `answer` where `answer[i]` is the number of days you have to wait after day `i` for a warmer temperature.",
      "If no warmer day comes later, `answer[i]` is `0`.",
    ],
    constraints: ["`1 <= temperatures.length <= 10^5`", "`30 <= temperatures[i] <= 100`"],
    hint: "Keep a stack of days still waiting for a warmer day, with temperatures decreasing from bottom to top. Each new day resolves every waiting day that is colder than it.",
    functionName: { js: "dailyTemperatures", py: "daily_temperatures" },
    params: [{ name: "temperatures", type: "int[]" }],
    returns: "int[]",
    tests: [
      { args: [[73, 74, 75, 71, 69, 72, 76, 73]], expected: [1, 1, 4, 2, 1, 1, 0, 0], example: true },
      { args: [[30, 40, 50, 60]], expected: [1, 1, 1, 0], example: true },
      { args: [[30, 60, 90]], expected: [1, 1, 0], example: true },
      { args: [[90, 80, 70]], expected: [0, 0, 0] },
      { args: [[50]], expected: [0] },
      { args: [[55, 38, 53, 81, 61, 93, 97, 32, 43, 78]], expected: [3, 1, 1, 2, 1, 1, 0, 1, 1, 0] },
    ],
  },
  {
    slug: "kth-largest-element-in-an-array",
    title: "Kth Largest Element",
    difficulty: "Medium",
    topics: ["Arrays", "Heap", "Sorting"],
    summary: "Find the kth largest number without fully sorting.",
    description: [
      "Given an integer array `nums` and an integer `k`, return the `k`th largest element in the array.",
      "This means the `k`th largest in sorted order, not the `k`th largest distinct value. Can you do better than sorting everything?",
    ],
    constraints: ["`1 <= k <= nums.length <= 10^5`", "`-10^4 <= nums[i] <= 10^4`"],
    hint: "Keep a min-heap of the `k` largest numbers seen so far; its smallest element is the answer. Quickselect is another option, with linear time on average.",
    functionName: { js: "findKthLargest", py: "find_kth_largest" },
    params: [
      { name: "nums", type: "int[]" },
      { name: "k", type: "int" },
    ],
    returns: "int",
    tests: [
      { args: [[3, 2, 1, 5, 6, 4], 2], expected: 5, example: true },
      { args: [[3, 2, 3, 1, 2, 4, 5, 5, 6], 4], expected: 4, example: true },
      { args: [[1], 1], expected: 1 },
      { args: [[7, 7, 7, 7], 2], expected: 7 },
      { args: [[-1, -5, -3], 1], expected: -1 },
      { args: [[9, 1, 8, 2, 7, 3, 6, 4, 5], 9], expected: 1 },
    ],
  },
  {
    slug: "coin-change",
    title: "Coin Change",
    difficulty: "Medium",
    topics: ["Dynamic programming"],
    summary: "Make an amount with as few coins as possible.",
    description: [
      "You're given coin denominations `coins` and a target `amount`. Return the fewest coins needed to make exactly `amount`, or `-1` if it can't be done.",
      "You have an unlimited supply of every denomination.",
    ],
    constraints: ["`1 <= coins.length <= 12`", "`1 <= coins[i] <= 2^31 - 1`", "`0 <= amount <= 10^4`"],
    hint: "Let `best[x]` be the fewest coins that make `x`. Then `best[x]` is 1 plus the minimum of `best[x - coin]` over every coin.",
    functionName: { js: "coinChange", py: "coin_change" },
    params: [
      { name: "coins", type: "int[]" },
      { name: "amount", type: "int" },
    ],
    returns: "int",
    tests: [
      { args: [[1, 2, 5], 11], expected: 3, example: true, explanation: "11 = 5 + 5 + 1." },
      { args: [[2], 3], expected: -1, example: true },
      { args: [[1], 0], expected: 0, example: true },
      { args: [[2, 5, 10, 1], 27], expected: 4 },
      { args: [[186, 419, 83, 408], 6249], expected: 20 },
      { args: [[3, 7], 5], expected: -1 },
      { args: [[1, 3, 4], 6], expected: 2 },
    ],
  },
  {
    slug: "house-robber",
    title: "House Robber",
    difficulty: "Medium",
    topics: ["Dynamic programming"],
    summary: "Collect the most money without ever taking from two neighbours.",
    description: [
      "Each house on a street has some money stashed in it, given by `nums`. You may take the money from any set of houses, as long as you never take from two houses that are next to each other.",
      "Return the largest total you can collect.",
    ],
    constraints: ["`1 <= nums.length <= 100`", "`0 <= nums[i] <= 400`"],
    hint: "For each house, the best total is either the best total up to the previous house, or this house's money plus the best total up to two houses back.",
    functionName: { js: "rob", py: "rob" },
    params: [{ name: "nums", type: "int[]" }],
    returns: "int",
    tests: [
      { args: [[1, 2, 3, 1]], expected: 4, example: true, explanation: "Take houses 0 and 2: 1 + 3 = 4." },
      { args: [[2, 7, 9, 3, 1]], expected: 12, example: true, explanation: "Take houses 0, 2 and 4: 2 + 9 + 1 = 12." },
      { args: [[5]], expected: 5 },
      { args: [[2, 1, 1, 2]], expected: 4 },
      { args: [[0, 0, 0]], expected: 0 },
      { args: [[6, 1, 2, 7]], expected: 13 },
      { args: [[100, 1, 1, 100]], expected: 200 },
    ],
  },
  {
    slug: "word-break",
    title: "Word Break",
    difficulty: "Medium",
    topics: ["Strings", "Dynamic programming"],
    summary: "Decide whether a string can be split into dictionary words.",
    description: [
      "Given a string `s` and a dictionary `words`, return `true` if `s` can be split into a sequence of one or more dictionary words, and `false` otherwise.",
      "The same dictionary word may be used more than once.",
    ],
    constraints: ["`1 <= s.length <= 300`", "`1 <= words.length <= 1000`", "All strings contain only lowercase English letters."],
    hint: "Let `ok[i]` mean the first `i` characters can be split. Then `ok[i]` is true when some earlier `ok[j]` is true and the piece from `j` to `i` is a dictionary word.",
    functionName: { js: "wordBreak", py: "word_break" },
    params: [
      { name: "s", type: "str" },
      { name: "words", type: "str[]" },
    ],
    returns: "bool",
    tests: [
      {
        args: ["codeshare", ["code", "share"]],
        expected: true,
        example: true,
        explanation: "\"codeshare\" is \"code\" + \"share\".",
      },
      {
        args: ["applepenapple", ["apple", "pen"]],
        expected: true,
        example: true,
        explanation: "Words can repeat: \"apple\" + \"pen\" + \"apple\".",
      },
      { args: ["catsandog", ["cats", "dog", "sand", "and", "cat"]], expected: false, example: true },
      { args: ["a", ["b"]], expected: false },
      { args: ["aaaaaaa", ["aaaa", "aaa"]], expected: true },
      { args: ["cars", ["car", "ca", "rs"]], expected: true },
      { args: ["goalspecial", ["go", "goal", "goals", "special"]], expected: true },
    ],
  },
  {
    slug: "subsets",
    title: "Subsets",
    difficulty: "Medium",
    topics: ["Backtracking", "Bit manipulation"],
    summary: "List every possible subset of a set of numbers.",
    description: [
      "Given an array `nums` of distinct integers, return every possible subset (the power set), including the empty one.",
      "The answer must not contain duplicate subsets. You can return the subsets in any order, and the numbers inside each subset in any order.",
    ],
    constraints: ["`1 <= nums.length <= 10`", "`-10 <= nums[i] <= 10`", "All numbers in `nums` are distinct."],
    hint: "Each number is either in a subset or not. Start from `[[]]` and, for each number, add a copy of every existing subset with that number appended.",
    functionName: { js: "subsets", py: "subsets" },
    params: [{ name: "nums", type: "int[]" }],
    returns: "int[][]",
    compare: "unordered-deep",
    tests: [
      { args: [[1, 2, 3]], expected: [[], [1], [2], [1, 2], [3], [1, 3], [2, 3], [1, 2, 3]], example: true },
      { args: [[0]], expected: [[], [0]], example: true },
      { args: [[5, -1]], expected: [[], [5], [-1], [5, -1]] },
      {
        args: [[1, 2, 3, 4]],
        expected: [
          [],
          [1],
          [2],
          [3],
          [4],
          [1, 2],
          [1, 3],
          [1, 4],
          [2, 3],
          [2, 4],
          [3, 4],
          [1, 2, 3],
          [1, 2, 4],
          [1, 3, 4],
          [2, 3, 4],
          [1, 2, 3, 4],
        ],
      },
    ],
  },
  {
    slug: "permutations",
    title: "Permutations",
    difficulty: "Medium",
    topics: ["Backtracking"],
    summary: "List every ordering of a set of numbers.",
    description: ["Given an array `nums` of distinct integers, return every possible permutation. You can return them in any order."],
    constraints: ["`1 <= nums.length <= 6`", "`-10 <= nums[i] <= 10`", "All numbers in `nums` are distinct."],
    hint: "Build permutations one position at a time. At each step try every number that isn't used yet, recurse, then undo the choice (backtrack).",
    functionName: { js: "permute", py: "permute" },
    params: [{ name: "nums", type: "int[]" }],
    returns: "int[][]",
    compare: "unordered",
    tests: [
      {
        args: [[1, 2, 3]],
        expected: [
          [1, 2, 3],
          [1, 3, 2],
          [2, 1, 3],
          [2, 3, 1],
          [3, 1, 2],
          [3, 2, 1],
        ],
        example: true,
      },
      { args: [[0, 1]], expected: [[0, 1], [1, 0]], example: true },
      { args: [[1]], expected: [[1]], example: true },
      { args: [[-1, 2]], expected: [[-1, 2], [2, -1]] },
      {
        args: [[4, 5, 6]],
        expected: [
          [4, 5, 6],
          [4, 6, 5],
          [5, 4, 6],
          [5, 6, 4],
          [6, 4, 5],
          [6, 5, 4],
        ],
      },
    ],
  },
  {
    slug: "combination-sum",
    title: "Combination Sum",
    difficulty: "Medium",
    topics: ["Backtracking"],
    summary: "Find every combination that adds up to a target, reusing numbers freely.",
    description: [
      "Given an array of distinct positive integers `candidates` and a `target`, return every unique combination of candidates that adds up to `target`. The same number may be used any number of times.",
      "Two combinations are the same if they use each number the same number of times. You can return the combinations in any order, and the numbers inside each combination in any order.",
    ],
    constraints: [
      "`1 <= candidates.length <= 30`",
      "`2 <= candidates[i] <= 40`",
      "All candidates are distinct.",
      "`1 <= target <= 40`",
    ],
    hint: "Backtrack over the candidates in order. At each step either use the current number again or move on to the next one, so each combination is built only once.",
    functionName: { js: "combinationSum", py: "combination_sum" },
    params: [
      { name: "candidates", type: "int[]" },
      { name: "target", type: "int" },
    ],
    returns: "int[][]",
    compare: "unordered-deep",
    tests: [
      { args: [[2, 3, 6, 7], 7], expected: [[2, 2, 3], [7]], example: true },
      { args: [[2, 3, 5], 8], expected: [[2, 2, 2, 2], [2, 3, 3], [3, 5]], example: true },
      { args: [[2], 1], expected: [], example: true },
      { args: [[3, 4, 5], 10], expected: [[3, 3, 4], [5, 5]] },
      { args: [[7, 8], 15], expected: [[7, 8]] },
      { args: [[2, 3], 6], expected: [[2, 2, 2], [3, 3]] },
    ],
  },
  {
    slug: "number-of-islands",
    title: "Number of Islands",
    difficulty: "Medium",
    topics: ["Graphs", "Matrix"],
    summary: "Count the groups of connected land on a map.",
    description: [
      "You're given a 2D `grid` of `1`s (land) and `0`s (water). An island is a group of land cells connected horizontally or vertically. Return the number of islands.",
      "Everything outside the grid counts as water, and diagonal neighbours are not connected.",
    ],
    constraints: ["`1 <= grid.length, grid[i].length <= 300`", "`grid[i][j]` is `0` or `1`."],
    hint: "Scan every cell. When you find unvisited land, count a new island and flood-fill (DFS or BFS) to mark all the land connected to it.",
    functionName: { js: "numIslands", py: "num_islands" },
    params: [{ name: "grid", type: "int[][]" }],
    returns: "int",
    tests: [
      {
        args: [[[1, 1, 1, 1, 0], [1, 1, 0, 1, 0], [1, 1, 0, 0, 0], [0, 0, 0, 0, 0]]],
        expected: 1,
        example: true,
      },
      {
        args: [[[1, 1, 0, 0, 0], [1, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 1]]],
        expected: 3,
        example: true,
      },
      { args: [[[0]]], expected: 0 },
      { args: [[[1]]], expected: 1 },
      { args: [[[1, 0, 1], [0, 1, 0], [1, 0, 1]]], expected: 5 },
      { args: [[[1, 1, 1], [0, 1, 0], [1, 1, 1]]], expected: 1 },
    ],
  },
  {
    slug: "rotting-oranges",
    title: "Rotting Oranges",
    difficulty: "Medium",
    topics: ["Graphs", "Matrix", "Queue"],
    summary: "Find how many minutes it takes for rot to spread to every orange.",
    description: [
      "You're given a grid where each cell is `0` (empty), `1` (a fresh orange) or `2` (a rotten orange). Every minute, each fresh orange next to a rotten one (up, down, left or right) becomes rotten.",
      "Return the minimum number of minutes until no fresh orange remains. If that can never happen, return `-1`.",
    ],
    constraints: ["`1 <= grid.length, grid[i].length <= 10`", "`grid[i][j]` is `0`, `1` or `2`."],
    hint: "Run a breadth-first search starting from all the rotten oranges at once. Each BFS layer is one minute; afterwards, check whether any fresh orange was never reached.",
    functionName: { js: "orangesRotting", py: "oranges_rotting" },
    params: [{ name: "grid", type: "int[][]" }],
    returns: "int",
    tests: [
      {
        args: [
          [
            [2, 1, 1],
            [1, 1, 0],
            [0, 1, 1],
          ],
        ],
        expected: 4,
        example: true,
      },
      {
        args: [
          [
            [2, 1, 1],
            [0, 1, 1],
            [1, 0, 1],
          ],
        ],
        expected: -1,
        example: true,
        explanation: "The orange in the bottom-left corner is never reached.",
      },
      { args: [[[0, 2]]], expected: 0, example: true, explanation: "There are no fresh oranges to begin with." },
      { args: [[[1]]], expected: -1 },
      {
        args: [
          [
            [2, 2],
            [1, 1],
          ],
        ],
        expected: 1,
      },
      { args: [[[2, 1, 0, 1, 2]]], expected: 1 },
      {
        args: [
          [
            [1, 1, 1],
            [1, 2, 1],
            [1, 1, 1],
          ],
        ],
        expected: 2,
      },
    ],
  },
  {
    slug: "course-schedule",
    title: "Course Schedule",
    difficulty: "Medium",
    topics: ["Graphs"],
    summary: "Decide whether every course can be finished, given the prerequisites.",
    description: [
      "There are `numCourses` courses labeled `0` to `numCourses - 1`. You're given an array `prerequisites` where `prerequisites[i] = [a, b]` means course `b` must be taken before course `a`.",
      "Return `true` if it's possible to finish every course, and `false` otherwise.",
    ],
    constraints: ["`1 <= numCourses <= 2000`", "`0 <= prerequisites.length <= 5000`", "All pairs `[a, b]` are distinct."],
    hint: "This is cycle detection in a directed graph. Repeatedly take the courses with no remaining prerequisites (Kahn's algorithm); if some courses never become available, there's a cycle.",
    functionName: { js: "canFinish", py: "can_finish" },
    params: [
      { name: "numCourses", type: "int" },
      { name: "prerequisites", type: "int[][]" },
    ],
    returns: "bool",
    tests: [
      { args: [2, [[1, 0]]], expected: true, example: true, explanation: "Take course 0, then course 1." },
      {
        args: [
          2,
          [
            [1, 0],
            [0, 1],
          ],
        ],
        expected: false,
        example: true,
        explanation: "Each course needs the other one first, so neither can start.",
      },
      { args: [1, []], expected: true },
      {
        args: [
          3,
          [
            [1, 0],
            [2, 1],
          ],
        ],
        expected: true,
      },
      {
        args: [
          3,
          [
            [0, 1],
            [1, 2],
            [2, 0],
          ],
        ],
        expected: false,
      },
      {
        args: [
          4,
          [
            [1, 0],
            [2, 0],
            [3, 1],
            [3, 2],
          ],
        ],
        expected: true,
      },
      {
        args: [
          5,
          [
            [1, 4],
            [2, 4],
            [3, 1],
            [3, 2],
            [4, 3],
          ],
        ],
        expected: false,
      },
    ],
  },
  {
    slug: "number-of-connected-components",
    title: "Connected Components",
    difficulty: "Medium",
    topics: ["Graphs", "Union find"],
    summary: "Count the separate groups in an undirected graph.",
    description: [
      "There are `n` nodes labeled `0` to `n - 1`, and an array `edges` where `edges[i] = [a, b]` is an undirected edge between nodes `a` and `b`.",
      "Return the number of connected components in the graph.",
    ],
    constraints: ["`1 <= n <= 2000`", "`0 <= edges.length <= 5000`", "No edge is repeated, and there are no self-loops."],
    hint: "Union-find works well: start with every node in its own set, merge the sets at the two ends of each edge, and count how many merges actually join two different sets.",
    functionName: { js: "countComponents", py: "count_components" },
    params: [
      { name: "n", type: "int" },
      { name: "edges", type: "int[][]" },
    ],
    returns: "int",
    tests: [
      {
        args: [
          5,
          [
            [0, 1],
            [1, 2],
            [3, 4],
          ],
        ],
        expected: 2,
        example: true,
      },
      {
        args: [
          5,
          [
            [0, 1],
            [1, 2],
            [2, 3],
            [3, 4],
          ],
        ],
        expected: 1,
        example: true,
      },
      { args: [3, []], expected: 3, example: true, explanation: "With no edges, every node is its own component." },
      { args: [1, []], expected: 1 },
      {
        args: [
          6,
          [
            [0, 1],
            [2, 3],
            [4, 5],
            [1, 2],
          ],
        ],
        expected: 2,
      },
      {
        args: [
          4,
          [
            [0, 1],
            [1, 2],
            [2, 0],
          ],
        ],
        expected: 2,
      },
    ],
  },
  {
    slug: "rotate-image",
    title: "Rotate Image",
    difficulty: "Medium",
    topics: ["Matrix", "Arrays"],
    summary: "Turn a square matrix 90 degrees clockwise, in place.",
    description: [
      "You're given an `n × n` matrix representing an image. Rotate it 90 degrees clockwise.",
      "Do this **in place**: change `matrix` directly instead of building a new one. The tests check `matrix` after your function finishes.",
    ],
    constraints: ["`1 <= n <= 20`", "`-1000 <= matrix[i][j] <= 1000`"],
    hint: "A clockwise rotation is the same as transposing the matrix (swapping `matrix[i][j]` with `matrix[j][i]`) and then reversing each row.",
    functionName: { js: "rotate", py: "rotate" },
    params: [{ name: "matrix", type: "int[][]" }],
    returns: "void",
    outputArg: 0,
    tests: [
      {
        args: [
          [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
          ],
        ],
        expected: [
          [7, 4, 1],
          [8, 5, 2],
          [9, 6, 3],
        ],
        example: true,
      },
      {
        args: [
          [
            [5, 1, 9, 11],
            [2, 4, 8, 10],
            [13, 3, 6, 7],
            [15, 14, 12, 16],
          ],
        ],
        expected: [
          [15, 13, 2, 5],
          [14, 3, 4, 1],
          [12, 6, 8, 9],
          [16, 7, 10, 11],
        ],
        example: true,
      },
      { args: [[[1]]], expected: [[1]] },
      {
        args: [
          [
            [1, 2],
            [3, 4],
          ],
        ],
        expected: [
          [3, 1],
          [4, 2],
        ],
      },
    ],
  },
  {
    slug: "remove-nth-node-from-end-of-list",
    title: "Remove Nth Node From End",
    difficulty: "Medium",
    topics: ["Linked list", "Two pointers"],
    summary: "Delete the node that is n places from the end of a linked list.",
    description: [
      "Given the `head` of a linked list, remove the `n`th node from the end of the list and return the head.",
      "Lists are written as arrays: `[1, 2, 3]` means `1 → 2 → 3`.",
    ],
    constraints: ["The list has between `1` and `30` nodes.", "`0 <= Node.val <= 100`", "`1 <= n <=` the length of the list"],
    hint: "Move a `fast` pointer `n` steps ahead, then move `fast` and `slow` together until `fast` reaches the end. A dummy node before the head makes removing the first node easy.",
    functionName: { js: "removeNthFromEnd", py: "remove_nth_from_end" },
    params: [
      { name: "head", type: "list" },
      { name: "n", type: "int" },
    ],
    returns: "list",
    tests: [
      { args: [[1, 2, 3, 4, 5], 2], expected: [1, 2, 3, 5], example: true },
      { args: [[1], 1], expected: [], example: true },
      { args: [[1, 2], 1], expected: [1], example: true },
      { args: [[1, 2], 2], expected: [2] },
      { args: [[10, 20, 30], 3], expected: [20, 30] },
      { args: [[4, 5, 6, 7], 1], expected: [4, 5, 6] },
    ],
  },
  {
    slug: "binary-tree-level-order-traversal",
    title: "Level Order Traversal",
    difficulty: "Medium",
    topics: ["Trees", "Queue"],
    summary: "Read a binary tree level by level, left to right.",
    description: [
      "Given the `root` of a binary tree, return its values level by level: an array of levels, each listing that level's values from left to right.",
      "Trees are written level by level, with `null` for a missing child.",
    ],
    constraints: ["The tree has between `0` and `2000` nodes.", "`-1000 <= Node.val <= 1000`"],
    hint: "Use a queue. Handle one level at a time: note how many nodes are in the queue, pop exactly that many, and push their children.",
    functionName: { js: "levelOrder", py: "level_order" },
    params: [{ name: "root", type: "tree" }],
    returns: "int[][]",
    tests: [
      { args: [[3, 9, 20, null, null, 15, 7]], expected: [[3], [9, 20], [15, 7]], example: true },
      { args: [[1]], expected: [[1]], example: true },
      { args: [[]], expected: [], example: true },
      { args: [[1, 2, 3, 4, null, null, 5]], expected: [[1], [2, 3], [4, 5]] },
      { args: [[1, 2, null, 3, null, 4]], expected: [[1], [2], [3], [4]] },
      {
        args: [[5, 4, 8, 11, null, 13, 4, 7, 2, null, null, null, 1]],
        expected: [[5], [4, 8], [11, 13, 4], [7, 2, 1]],
      },
    ],
  },
  {
    slug: "validate-binary-search-tree",
    title: "Validate Binary Search Tree",
    difficulty: "Medium",
    topics: ["Trees"],
    summary: "Check whether a binary tree follows the search-tree ordering rule.",
    description: [
      "Given the `root` of a binary tree, decide whether it is a valid binary search tree (BST).",
      "In a valid BST, a node's left subtree contains only values strictly less than the node's value, its right subtree contains only values strictly greater, and both subtrees are valid BSTs themselves.",
    ],
    constraints: ["The tree has between `1` and `10^4` nodes.", "`-2^31 <= Node.val <= 2^31 - 1`"],
    hint: "Comparing each node with its direct children isn't enough. Pass down the range `(low, high)` that each subtree must fall within, or check that an in-order traversal is strictly increasing.",
    functionName: { js: "isValidBST", py: "is_valid_bst" },
    params: [{ name: "root", type: "tree" }],
    returns: "bool",
    tests: [
      { args: [[2, 1, 3]], expected: true, example: true },
      {
        args: [[5, 1, 4, null, null, 3, 6]],
        expected: false,
        example: true,
        explanation: "The root is 5, but its right child 4 is smaller than 5.",
      },
      { args: [[1]], expected: true },
      { args: [[1, 1]], expected: false },
      { args: [[5, 4, 6, null, null, 3, 7]], expected: false },
      { args: [[10, 5, 15, 2, 7, 12, 20]], expected: true },
      { args: [[2147483647]], expected: true },
    ],
  },
];