import type { Problem } from "@/lib/problems";

// The second set of Medium problems.
export const MEDIUM_PROBLEMS_2: Problem[] = [
  {
    slug: "longest-palindromic-substring",
    title: "Longest Palindromic Substring",
    difficulty: "Medium",
    topics: ["Strings", "Dynamic programming"],
    summary: "Find the longest part of a string that reads the same backward.",
    description: [
      "Given a string `s`, return its longest palindromic substring: the longest run of consecutive characters that reads the same forward and backward.",
      "Every test has exactly one answer.",
    ],
    constraints: ["`1 <= s.length <= 1000`", "`s` contains only digits and English letters."],
    hint: "Every palindrome has a center: a single character, or the gap between two equal characters. Expand outward from each of the `2n - 1` centers and keep the longest.",
    functionName: { js: "longestPalindrome", py: "longest_palindrome" },
    params: [{ name: "s", type: "str" }],
    returns: "str",
    tests: [
      { args: ["cbbd"], expected: "bb", example: true },
      { args: ["forgeeksskeegfor"], expected: "geeksskeeg", example: true },
      { args: ["a"], expected: "a", example: true },
      { args: ["racecarxyz"], expected: "racecar" },
      { args: ["abacdfgdcaba"], expected: "aba" },
      { args: ["aaaa"], expected: "aaaa" },
    ],
  },
  {
    slug: "set-matrix-zeroes",
    title: "Set Matrix Zeroes",
    difficulty: "Medium",
    topics: ["Matrix", "Arrays"],
    summary: "Zero out the whole row and column of every 0, in place.",
    description: [
      "Given an `m × n` integer matrix, whenever an element is `0`, set its entire row and column to `0`.",
      "Do this **in place**: change `matrix` directly. The tests check `matrix` after your function finishes. Can you use only `O(1)` extra space?",
    ],
    constraints: ["`1 <= m, n <= 200`", "`-2^31 <= matrix[i][j] <= 2^31 - 1`"],
    hint: "First record which rows and columns contain a zero (two sets are fine), then zero them in a second pass. For `O(1)` space, use the first row and column as the record.",
    functionName: { js: "setZeroes", py: "set_zeroes" },
    params: [{ name: "matrix", type: "int[][]" }],
    returns: "void",
    outputArg: 0,
    tests: [
      {
        args: [
          [
            [1, 1, 1],
            [1, 0, 1],
            [1, 1, 1],
          ],
        ],
        expected: [
          [1, 0, 1],
          [0, 0, 0],
          [1, 0, 1],
        ],
        example: true,
      },
      {
        args: [
          [
            [0, 1, 2, 0],
            [3, 4, 5, 2],
            [1, 3, 1, 5],
          ],
        ],
        expected: [
          [0, 0, 0, 0],
          [0, 4, 5, 0],
          [0, 3, 1, 0],
        ],
        example: true,
      },
      { args: [[[1]]], expected: [[1]] },
      { args: [[[0]]], expected: [[0]] },
      {
        args: [
          [
            [1, 2],
            [3, 0],
          ],
        ],
        expected: [
          [1, 0],
          [0, 0],
        ],
      },
    ],
  },
  {
    slug: "spiral-matrix",
    title: "Spiral Matrix",
    difficulty: "Medium",
    topics: ["Matrix", "Arrays"],
    summary: "Read a matrix in clockwise spiral order.",
    description: [
      "Given an `m × n` matrix, return all of its elements in spiral order: along the top row, down the right column, back along the bottom row, up the left column, and so on inward.",
    ],
    constraints: ["`1 <= m, n <= 10`", "`-100 <= matrix[i][j] <= 100`"],
    hint: "Keep four boundaries (top, bottom, left, right). Walk one side, then move that boundary inward, until the boundaries cross.",
    functionName: { js: "spiralOrder", py: "spiral_order" },
    params: [{ name: "matrix", type: "int[][]" }],
    returns: "int[]",
    tests: [
      {
        args: [
          [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
          ],
        ],
        expected: [1, 2, 3, 6, 9, 8, 7, 4, 5],
        example: true,
      },
      {
        args: [
          [
            [1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12],
          ],
        ],
        expected: [1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7],
        example: true,
      },
      { args: [[[7]]], expected: [7] },
      {
        args: [
          [
            [1, 2],
            [3, 4],
          ],
        ],
        expected: [1, 2, 4, 3],
      },
      { args: [[[1], [2], [3]]], expected: [1, 2, 3] },
    ],
  },
  {
    slug: "jump-game",
    title: "Jump Game",
    difficulty: "Medium",
    topics: ["Arrays", "Greedy"],
    summary: "Can you hop from the first index to the last?",
    description: [
      "You start at the first index of the array `nums`. Each element is your maximum jump length from that position.",
      "Return `true` if you can reach the last index, and `false` otherwise.",
    ],
    constraints: ["`1 <= nums.length <= 10^4`", "`0 <= nums[i] <= 10^5`"],
    hint: "Walk left to right keeping the farthest index you can reach so far. If you ever stand on an index beyond that reach, you're stuck.",
    functionName: { js: "canJump", py: "can_jump" },
    params: [{ name: "nums", type: "int[]" }],
    returns: "bool",
    tests: [
      {
        args: [[2, 3, 1, 1, 4]],
        expected: true,
        example: true,
        explanation: "Jump 1 step to index 1, then 3 steps to the last index.",
      },
      {
        args: [[3, 2, 1, 0, 4]],
        expected: false,
        example: true,
        explanation: "Every path lands on index 3, whose jump length is 0.",
      },
      { args: [[0]], expected: true },
      { args: [[1, 0, 1]], expected: false },
      { args: [[2, 0, 0]], expected: true },
      { args: [[1, 1, 1, 1]], expected: true },
    ],
  },
  {
    slug: "unique-paths",
    title: "Unique Paths",
    difficulty: "Medium",
    topics: ["Dynamic programming", "Math"],
    summary: "Count the paths across a grid moving only right or down.",
    description: [
      "A robot starts at the top-left corner of an `m × n` grid and wants to reach the bottom-right corner. It can only move right or down.",
      "Return the number of different paths it can take.",
    ],
    constraints: ["`1 <= m, n <= 100`", "The answer is at most `2 * 10^9`."],
    hint: "The number of ways to reach a cell is the ways to reach the cell above it plus the ways to reach the cell to its left. Every cell in the first row and column has exactly one way.",
    functionName: { js: "uniquePaths", py: "unique_paths" },
    params: [
      { name: "m", type: "int" },
      { name: "n", type: "int" },
    ],
    returns: "int",
    tests: [
      { args: [3, 7], expected: 28, example: true },
      {
        args: [3, 2],
        expected: 3,
        example: true,
        explanation: "Right → Down → Down, Down → Down → Right, or Down → Right → Down.",
      },
      { args: [1, 1], expected: 1 },
      { args: [7, 3], expected: 28 },
      { args: [10, 10], expected: 48620 },
    ],
  },
  {
    slug: "longest-increasing-subsequence",
    title: "Longest Increasing Subsequence",
    difficulty: "Medium",
    topics: ["Dynamic programming", "Binary search"],
    summary: "Find the length of the longest strictly increasing subsequence.",
    description: [
      "Given an integer array `nums`, return the length of its longest strictly increasing subsequence.",
      "A subsequence keeps the original order but may skip elements: `[3, 6, 2, 7]` is a subsequence of `[0, 3, 1, 6, 2, 2, 7]`.",
    ],
    constraints: ["`1 <= nums.length <= 2500`", "`-10^4 <= nums[i] <= 10^4`"],
    hint: "In `O(n²)`: the best length ending at `i` is one more than the best ending at any earlier, smaller value. In `O(n log n)`: keep the smallest possible tail for each length, and binary search where each number goes.",
    functionName: { js: "lengthOfLIS", py: "length_of_lis" },
    params: [{ name: "nums", type: "int[]" }],
    returns: "int",
    tests: [
      {
        args: [[10, 9, 2, 5, 3, 7, 101, 18]],
        expected: 4,
        example: true,
        explanation: "One longest increasing subsequence is [2, 3, 7, 101].",
      },
      { args: [[0, 1, 0, 3, 2, 3]], expected: 4, example: true },
      { args: [[7, 7, 7, 7, 7, 7, 7]], expected: 1, example: true },
      { args: [[1]], expected: 1 },
      { args: [[4, 10, 4, 3, 8, 9]], expected: 3 },
      { args: [[1, 3, 6, 7, 9, 4, 10, 5, 6]], expected: 6 },
    ],
  },
  {
    slug: "decode-ways",
    title: "Decode Ways",
    difficulty: "Medium",
    topics: ["Dynamic programming", "Strings"],
    summary: "Count the ways a string of digits can be read as letters.",
    description: [
      "Letters are encoded as numbers: `A` is `1`, `B` is `2`, and so on up to `Z` as `26`. Given a string `s` of digits, return the number of ways to decode it back into letters.",
      "A group can't start with `0`: `06` isn't a valid code for `F`. If `s` can't be decoded at all, return `0`.",
    ],
    constraints: ["`1 <= s.length <= 100`", "`s` contains only digits, and may contain leading zeros."],
    hint: "Let `ways[i]` be the number of ways to decode the first `i` digits. The last digit alone adds `ways[i - 1]` if it isn't `0`, and the last two digits together add `ways[i - 2]` if they form a number from 10 to 26.",
    functionName: { js: "numDecodings", py: "num_decodings" },
    params: [{ name: "s", type: "str" }],
    returns: "int",
    tests: [
      { args: ["12"], expected: 2, example: true, explanation: "It can be read as AB (1 2) or L (12)." },
      { args: ["226"], expected: 3, example: true, explanation: "BZ (2 26), VF (22 6), or BBF (2 2 6)." },
      { args: ["06"], expected: 0, example: true, explanation: "No group can start with 0." },
      { args: ["0"], expected: 0 },
      { args: ["10"], expected: 1 },
      { args: ["11106"], expected: 2 },
      { args: ["2101"], expected: 1 },
    ],
  },
  {
    slug: "find-minimum-in-rotated-sorted-array",
    title: "Find Minimum in Rotated Sorted Array",
    difficulty: "Medium",
    topics: ["Arrays", "Binary search"],
    summary: "Find the smallest value in a sorted array that was rotated.",
    description: [
      "A sorted array of distinct numbers was rotated some number of times: `[0, 1, 2, 4, 5, 6, 7]` might have become `[4, 5, 6, 7, 0, 1, 2]`.",
      "Given the rotated array `nums`, return its minimum element in `O(log n)` time.",
    ],
    constraints: ["`1 <= nums.length <= 5000`", "`-5000 <= nums[i] <= 5000`", "All values are distinct."],
    hint: "Compare the middle element with the last one. If it's bigger, the minimum is to the right of the middle; otherwise it's the middle itself or to its left.",
    functionName: { js: "findMin", py: "find_min" },
    params: [{ name: "nums", type: "int[]" }],
    returns: "int",
    tests: [
      { args: [[3, 4, 5, 1, 2]], expected: 1, example: true },
      { args: [[4, 5, 6, 7, 0, 1, 2]], expected: 0, example: true },
      {
        args: [[11, 13, 15, 17]],
        expected: 11,
        example: true,
        explanation: "The array was rotated a full cycle, so it's still sorted.",
      },
      { args: [[2, 1]], expected: 1 },
      { args: [[1]], expected: 1 },
      { args: [[5, 1, 2, 3, 4]], expected: 1 },
    ],
  },
  {
    slug: "generate-parentheses",
    title: "Generate Parentheses",
    difficulty: "Medium",
    topics: ["Backtracking", "Strings"],
    summary: "List every valid combination of n pairs of parentheses.",
    description: [
      "Given `n` pairs of parentheses, return every combination of well-formed parentheses.",
      "You can return the combinations in any order.",
    ],
    constraints: ["`1 <= n <= 8`"],
    hint: "Build strings one character at a time. You can add `(` while fewer than `n` are open, and `)` while more have opened than closed.",
    functionName: { js: "generateParenthesis", py: "generate_parenthesis" },
    params: [{ name: "n", type: "int" }],
    returns: "str[]",
    compare: "unordered",
    tests: [
      { args: [3], expected: ["((()))", "(()())", "(())()", "()(())", "()()()"], example: true },
      { args: [1], expected: ["()"], example: true },
      { args: [2], expected: ["(())", "()()"] },
      {
        args: [4],
        expected: [
          "(((())))",
          "((()()))",
          "((())())",
          "((()))()",
          "(()(()))",
          "(()()())",
          "(()())()",
          "(())(())",
          "(())()()",
          "()((()))",
          "()(()())",
          "()(())()",
          "()()(())",
          "()()()()",
        ],
      },
    ],
  },
  {
    slug: "letter-combinations-of-a-phone-number",
    title: "Letter Combinations of a Phone Number",
    difficulty: "Medium",
    topics: ["Backtracking", "Strings", "Hash map"],
    summary: "List every word a string of phone digits could spell.",
    description: [
      "Given a string of digits from `2` to `9`, return every letter combination the digits could represent, using the letters on a phone keypad: `2` is `abc`, `3` is `def`, `4` is `ghi`, `5` is `jkl`, `6` is `mno`, `7` is `pqrs`, `8` is `tuv` and `9` is `wxyz`.",
      "You can return the combinations in any order. An empty string of digits has no combinations.",
    ],
    constraints: ["`0 <= digits.length <= 4`", "Each digit is between `2` and `9`."],
    hint: "Backtracking: for the next digit, try each of its letters and recurse on the rest. When every digit has a letter, you have a finished combination.",
    functionName: { js: "letterCombinations", py: "letter_combinations" },
    params: [{ name: "digits", type: "str" }],
    returns: "str[]",
    compare: "unordered",
    tests: [
      { args: ["23"], expected: ["ad", "ae", "af", "bd", "be", "bf", "cd", "ce", "cf"], example: true },
      { args: [""], expected: [], example: true },
      { args: ["2"], expected: ["a", "b", "c"], example: true },
      {
        args: ["79"],
        expected: ["pw", "px", "py", "pz", "qw", "qx", "qy", "qz", "rw", "rx", "ry", "rz", "sw", "sx", "sy", "sz"],
      },
    ],
  },
  {
    slug: "word-search",
    title: "Word Search",
    difficulty: "Medium",
    topics: ["Backtracking", "Matrix"],
    summary: "Find a word in a grid of letters by moving between neighbors.",
    description: [
      "Given an `m × n` grid of characters `board` and a string `word`, return `true` if `word` can be traced in the grid.",
      "The word is built from letters in sequentially adjacent cells, where adjacent means horizontally or vertically neighboring. The same cell can't be used twice in one word.",
    ],
    constraints: ["`1 <= m, n <= 6`", "`1 <= word.length <= 15`", "`board` and `word` contain only English letters."],
    hint: "Try every cell as a start and run a depth-first search that matches one letter per step. Mark a cell as used while it's on the current path, and unmark it when you backtrack.",
    functionName: { js: "exist", py: "exist" },
    params: [
      { name: "board", type: "str[][]" },
      { name: "word", type: "str" },
    ],
    returns: "bool",
    tests: [
      {
        args: [
          [
            ["A", "B", "C", "E"],
            ["S", "F", "C", "S"],
            ["A", "D", "E", "E"],
          ],
          "ABCCED",
        ],
        expected: true,
        example: true,
      },
      {
        args: [
          [
            ["A", "B", "C", "E"],
            ["S", "F", "C", "S"],
            ["A", "D", "E", "E"],
          ],
          "SEE",
        ],
        expected: true,
        example: true,
      },
      {
        args: [
          [
            ["A", "B", "C", "E"],
            ["S", "F", "C", "S"],
            ["A", "D", "E", "E"],
          ],
          "ABCB",
        ],
        expected: false,
        example: true,
        explanation: "Spelling ABCB would need to use the B twice.",
      },
      { args: [[["a"]], "a"], expected: true },
      {
        args: [
          [
            ["a", "b"],
            ["c", "d"],
          ],
          "abdc",
        ],
        expected: true,
      },
      { args: [[["a", "a"]], "aaa"], expected: false },
    ],
  },
  {
    slug: "sort-colors",
    title: "Sort Colors",
    difficulty: "Medium",
    topics: ["Arrays", "Two pointers", "Sorting"],
    summary: "Sort an array of 0s, 1s and 2s in a single pass.",
    description: [
      "The array `nums` holds objects colored red, white or blue, written as `0`, `1` and `2`. Sort them **in place** so that objects of the same color are together, in the order red, white, blue.",
      "Don't use the library's sort. The tests check `nums` after your function finishes. Can you do it in one pass?",
    ],
    constraints: ["`1 <= nums.length <= 300`", "Each `nums[i]` is `0`, `1` or `2`."],
    hint: "The Dutch national flag algorithm: keep a boundary for the 0s at the front and one for the 2s at the back. Swap each 0 forward and each 2 backward as you scan the middle.",
    functionName: { js: "sortColors", py: "sort_colors" },
    params: [{ name: "nums", type: "int[]" }],
    returns: "void",
    outputArg: 0,
    tests: [
      { args: [[2, 0, 2, 1, 1, 0]], expected: [0, 0, 1, 1, 2, 2], example: true },
      { args: [[2, 0, 1]], expected: [0, 1, 2], example: true },
      { args: [[0]], expected: [0] },
      { args: [[1, 1]], expected: [1, 1] },
      { args: [[2, 2, 0]], expected: [0, 2, 2] },
    ],
  },
  {
    slug: "evaluate-reverse-polish-notation",
    title: "Evaluate Reverse Polish Notation",
    difficulty: "Medium",
    topics: ["Stack", "Math"],
    summary: "Compute an arithmetic expression written in postfix order.",
    description: [
      "You're given an arithmetic expression as an array of tokens in Reverse Polish Notation, where each operator comes after its two operands: the tokens `2`, `1`, `+` mean `2 + 1`.",
      "The operators are `+`, `-`, `*` and `/`. Division between two integers truncates toward zero, and there's never a division by zero. Return the value of the expression.",
    ],
    constraints: [
      "`1 <= tokens.length <= 10^4`",
      "Each token is an operator or an integer in the range `[-200, 200]`.",
      "The expression is always valid.",
    ],
    hint: "Push numbers onto a stack. For an operator, pop two numbers (the second one you pop is the left operand), apply it, and push the result.",
    functionName: { js: "evalRPN", py: "eval_rpn" },
    params: [{ name: "tokens", type: "str[]" }],
    returns: "int",
    tests: [
      { args: [["2", "1", "+", "3", "*"]], expected: 9, example: true, explanation: "(2 + 1) * 3 = 9." },
      { args: [["4", "13", "5", "/", "+"]], expected: 6, example: true, explanation: "4 + (13 / 5) = 4 + 2 = 6." },
      {
        args: [["10", "6", "9", "3", "+", "-11", "*", "/", "*", "17", "+", "5", "+"]],
        expected: 22,
        example: true,
      },
      { args: [["3"]], expected: 3 },
      { args: [["7", "-3", "/"]], expected: -2 },
      { args: [["2", "3", "-"]], expected: -1 },
    ],
  },
  {
    slug: "kth-smallest-element-in-a-bst",
    title: "Kth Smallest Element in a BST",
    difficulty: "Medium",
    topics: ["Trees", "Stack"],
    summary: "Find the kth smallest value in a binary search tree.",
    description: [
      "Given the `root` of a binary search tree and an integer `k`, return the `k`th smallest value in the tree, counting from 1.",
      "Trees are written level by level, with `null` for a missing child.",
    ],
    constraints: ["The tree has `n` nodes, with `1 <= k <= n <= 10^4`.", "`0 <= Node.val <= 10^4`"],
    hint: "An in-order traversal of a binary search tree visits the values in sorted order. Stop at the `k`th node you visit.",
    functionName: { js: "kthSmallest", py: "kth_smallest" },
    params: [
      { name: "root", type: "tree" },
      { name: "k", type: "int" },
    ],
    returns: "int",
    tests: [
      { args: [[3, 1, 4, null, 2], 1], expected: 1, example: true },
      { args: [[5, 3, 6, 2, 4, null, null, 1], 3], expected: 3, example: true },
      { args: [[1], 1], expected: 1 },
      { args: [[5, 3, 6, 2, 4, null, null, 1], 6], expected: 6 },
      { args: [[2, 1, 3], 2], expected: 2 },
    ],
  },
  {
    slug: "binary-tree-right-side-view",
    title: "Binary Tree Right Side View",
    difficulty: "Medium",
    topics: ["Trees", "Queue"],
    summary: "List the nodes you'd see looking at a tree from the right.",
    description: [
      "Given the `root` of a binary tree, imagine standing on its right side. Return the values of the nodes you can see, from top to bottom: the last node on each level.",
      "Trees are written level by level, with `null` for a missing child.",
    ],
    constraints: ["The tree has between `0` and `100` nodes.", "`-100 <= Node.val <= 100`"],
    hint: "Do a level-order traversal (breadth-first, one level at a time) and record the last node of each level.",
    functionName: { js: "rightSideView", py: "right_side_view" },
    params: [{ name: "root", type: "tree" }],
    returns: "int[]",
    tests: [
      { args: [[1, 2, 3, null, 5, null, 4]], expected: [1, 3, 4], example: true },
      { args: [[1, null, 3]], expected: [1, 3], example: true },
      { args: [[]], expected: [], example: true },
      { args: [[1, 2, 3, 4]], expected: [1, 3, 4] },
      { args: [[1, 2]], expected: [1, 2] },
    ],
  },
  {
    slug: "construct-binary-tree-from-preorder-and-inorder-traversal",
    title: "Construct Binary Tree from Preorder and Inorder Traversal",
    difficulty: "Medium",
    topics: ["Trees", "Hash map"],
    summary: "Rebuild a binary tree from two of its traversals.",
    description: [
      "Given two integer arrays `preorder` and `inorder`, the preorder and inorder traversals of the same binary tree, build the tree and return its root.",
      "Trees are written level by level, with `null` for a missing child. Every value in the tree is unique.",
    ],
    constraints: [
      "`1 <= preorder.length <= 3000`",
      "`inorder.length == preorder.length`",
      "`-3000 <= preorder[i], inorder[i] <= 3000`",
      "Values are unique, and both arrays describe the same tree.",
    ],
    hint: "The first value in `preorder` is the root. Its position in `inorder` splits the rest into the left and right subtrees, which you build the same way. A map from value to inorder index makes each split instant.",
    functionName: { js: "buildTree", py: "build_tree" },
    params: [
      { name: "preorder", type: "int[]" },
      { name: "inorder", type: "int[]" },
    ],
    returns: "tree",
    tests: [
      {
        args: [
          [3, 9, 20, 15, 7],
          [9, 3, 15, 20, 7],
        ],
        expected: [3, 9, 20, null, null, 15, 7],
        example: true,
      },
      { args: [[-1], [-1]], expected: [-1], example: true },
      {
        args: [
          [1, 2],
          [2, 1],
        ],
        expected: [1, 2],
      },
      {
        args: [
          [1, 2],
          [1, 2],
        ],
        expected: [1, null, 2],
      },
      {
        args: [
          [1, 2, 4, 5, 3, 6],
          [4, 2, 5, 1, 6, 3],
        ],
        expected: [1, 2, 3, 4, 5, 6],
      },
    ],
  },
  {
    slug: "add-two-numbers",
    title: "Add Two Numbers",
    difficulty: "Medium",
    topics: ["Linked list", "Math"],
    summary: "Add two numbers stored as linked lists of digits.",
    description: [
      "You're given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, one digit per node: `[2, 4, 3]` is the number `342`.",
      "Add the two numbers and return the sum as a linked list in the same format. Lists are written as arrays in the examples.",
    ],
    constraints: [
      "Each list has between `1` and `100` nodes.",
      "`0 <= Node.val <= 9`",
      "The numbers have no leading zeros, except the number `0` itself.",
    ],
    hint: "Walk both lists together, adding digit by digit like on paper. Keep a carry, and don't forget a final carry at the end.",
    functionName: { js: "addTwoNumbers", py: "add_two_numbers" },
    params: [
      { name: "l1", type: "list" },
      { name: "l2", type: "list" },
    ],
    returns: "list",
    tests: [
      {
        args: [
          [2, 4, 3],
          [5, 6, 4],
        ],
        expected: [7, 0, 8],
        example: true,
        explanation: "342 + 465 = 807.",
      },
      { args: [[0], [0]], expected: [0], example: true },
      {
        args: [
          [9, 9, 9, 9, 9, 9, 9],
          [9, 9, 9, 9],
        ],
        expected: [8, 9, 9, 9, 0, 0, 0, 1],
        example: true,
      },
      { args: [[1], [9, 9]], expected: [0, 0, 1] },
      { args: [[5], [5]], expected: [0, 1] },
    ],
  },
  {
    slug: "network-delay-time",
    title: "Network Delay Time",
    difficulty: "Medium",
    topics: ["Graphs", "Heap"],
    summary: "How long until a signal reaches every node of a network?",
    description: [
      "A network has `n` nodes, labeled `1` to `n`. You're given `times`, a list of directed edges `[u, v, w]`: a signal takes `w` time to travel from `u` to `v`.",
      "A signal is sent from node `k`. Return how long it takes for every node to receive it, or `-1` if some node never does.",
    ],
    constraints: [
      "`1 <= k <= n <= 100`",
      "`1 <= times.length <= 6000`",
      "`1 <= w <= 100`",
      "There's at most one edge from any `u` to any `v`.",
    ],
    hint: "Dijkstra's algorithm: a min-heap of (time, node) pairs pops each node at its earliest arrival time. The answer is the latest of those times, if every node was reached.",
    functionName: { js: "networkDelayTime", py: "network_delay_time" },
    params: [
      { name: "times", type: "int[][]" },
      { name: "n", type: "int" },
      { name: "k", type: "int" },
    ],
    returns: "int",
    tests: [
      {
        args: [
          [
            [2, 1, 1],
            [2, 3, 1],
            [3, 4, 1],
          ],
          4,
          2,
        ],
        expected: 2,
        example: true,
      },
      { args: [[[1, 2, 1]], 2, 1], expected: 1, example: true },
      {
        args: [[[1, 2, 1]], 2, 2],
        expected: -1,
        example: true,
        explanation: "The only edge goes from 1 to 2, so node 1 never hears the signal.",
      },
      {
        args: [
          [
            [1, 2, 1],
            [2, 3, 2],
            [1, 3, 4],
          ],
          3,
          1,
        ],
        expected: 3,
      },
      {
        args: [
          [
            [1, 2, 5],
            [1, 3, 1],
            [3, 2, 1],
          ],
          3,
          1,
        ],
        expected: 2,
      },
    ],
  },
];