import type { Problem } from "@/lib/problems";

// What an interviewer needs for each Practice problem: a ladder of three
// hints (a gentle nudge, a direction, then the problem's own hint), the
// approach with its target complexity, and follow-up questions for a strong
// candidate. Only the interviewer sees the approach and the follow-ups.

export type InterviewKit = {
  hints: string[];
  approach: string;
  time: string;
  space: string;
  followUps: string[];
};

type Kit = Omit<InterviewKit, "hints"> & { nudge: string; direction: string };

const kit = (
  nudge: string,
  direction: string,
  approach: string,
  time: string,
  space: string,
  followUps: string[],
): Kit => ({ nudge, direction, approach, time, space, followUps });

const KITS: Record<string, Kit> = {
  // ---------- Easy ----------
  "two-sum": kit(
    "What would make it quick to check whether you've already seen a number's partner?",
    "For each number, the partner you need is `target - number`. Can you look that up in constant time?",
    "One pass with a hash map from value to index: before storing each number, check whether its partner is already in the map.",
    "O(n)", "O(n)",
    ["What if the array were sorted? (Two pointers, with O(1) extra space.)", "What if you had to return every pair that adds up to the target?"],
  ),
  "valid-parentheses": kit(
    "When you meet a closing bracket, which opening bracket does it have to match?",
    "The most recent unmatched opener must close first. Which data structure gives you the most recent item?",
    "A stack of opening brackets: push openers; a closer must match the top, which is popped. Valid when the stack ends empty.",
    "O(n)", "O(n)",
    ["With only one kind of bracket, can you do it in O(1) space? (A counter.)", "How would you report the position of the first error?"],
  ),
  "valid-anagram": kit(
    "What do two anagrams have in common, letter by letter?",
    "Anagrams use each letter the same number of times. How could you compare those counts?",
    "Count each letter of `s` and subtract each letter of `t` in a 26-slot array (or a map); every count must end at zero.",
    "O(n)", "O(1)",
    ["What changes if the strings can contain any Unicode character?", "Sorting both strings also works. What does it cost?"],
  ),
  "binary-search": kit(
    "The array is sorted. What does one comparison with the middle element tell you?",
    "Each comparison rules out half of the remaining range. Keep a `low` and a `high` and shrink them.",
    "Classic binary search: compare `target` with the middle and discard the half that can't contain it, until the range is empty.",
    "O(log n)", "O(1)",
    ["With duplicates, how do you find the first (or last) occurrence?", "Why is `low + (high - low) / 2` safer than `(low + high) / 2` in some languages?"],
  ),
  "best-time-to-buy-and-sell-stock": kit(
    "If you knew the day you sell, which day would you want to have bought on?",
    "The best buy for any sale day is the lowest price before it. Can you track that as you go?",
    "One pass keeping the minimum price so far; the best profit is the maximum of `price - minSoFar`.",
    "O(n)", "O(1)",
    ["What if you could buy and sell as many times as you like?", "What if you were allowed at most two transactions?"],
  ),
  "valid-palindrome": kit(
    "Which characters actually matter for the comparison?",
    "Compare from both ends at once, skipping anything that isn't a letter or digit.",
    "Two pointers moving inward, skipping non-alphanumerics and comparing case-insensitively.",
    "O(n)", "O(1)",
    ["What if you're allowed to delete at most one character?", "Why avoid building a cleaned copy of the string first?"],
  ),
  "climbing-stairs": kit(
    "Think about your very last move onto step `n`. Where could you have come from?",
    "The count for `n` builds on the counts for smaller steps, so you only need the previous two values.",
    "Fibonacci-style DP: `ways(n) = ways(n - 1) + ways(n - 2)`, keeping just the last two values.",
    "O(n)", "O(1)",
    ["What if you could climb 1, 2 or 3 steps at a time (or any set of step sizes)?", "Can you compute it in O(log n)? (Matrix exponentiation.)"],
  ),
  "missing-number": kit(
    "If no number were missing, what would all the numbers add up to?",
    "The sum of `0` to `n` has a simple formula. Compare it with the sum you actually have.",
    "Subtract the array's sum from `n * (n + 1) / 2` (or XOR every index with every value).",
    "O(n)", "O(1)",
    ["The sum could overflow in some languages. How does XOR avoid that?", "What if two numbers were missing?"],
  ),
  "first-unique-character": kit(
    "To know a character is unique, what do you need to know about the whole string?",
    "Count every character first, then look for the first one whose count is 1.",
    "Two passes: count characters (an array of 26, or a map), then return the first index with a count of 1.",
    "O(n)", "O(1)",
    ["How would you handle a stream of characters, answering after each one?", "Could you do it in a single pass over the string?"],
  ),
  "roman-to-integer": kit(
    "When is a symbol's value subtracted instead of added? Look at `IV` and `VI`.",
    "Compare each symbol with the one after it: smaller before larger means subtract.",
    "Map each symbol to its value and scan left to right, subtracting a value when the next one is larger.",
    "O(n)", "O(1)",
    ["How would you convert an integer to Roman numerals?", "How would you reject an invalid numeral like `IIV`?"],
  ),
  "single-number": kit(
    "Which operation cancels a number out when it's applied twice?",
    "XOR does: `x ^ x = 0`. What's left after XOR-ing everything together?",
    "XOR all the numbers; every pair cancels and the single number remains.",
    "O(n)", "O(1)",
    ["What if every other number appeared three times?", "What if there were two single numbers?"],
  ),
  "counting-bits": kit(
    "How is the binary form of `i` related to the binary form of `i / 2`?",
    "Shifting right drops the last bit. So `ans[i]` relates to `ans[i >> 1]` plus that last bit.",
    "DP over `i`: `ans[i] = ans[i >> 1] + (i & 1)` (or `ans[i & (i - 1)] + 1`).",
    "O(n)", "O(1)",
    ["Why does `i & (i - 1)` remove the lowest set bit?", "What does a built-in popcount cost per number?"],
  ),
  "move-zeroes": kit(
    "Can you collect the non-zero numbers at the front without changing their order?",
    "Keep a write position for the next non-zero number and fill the rest with zeros afterwards.",
    "Two pointers: copy (or swap) each non-zero number to the write position, then zero out the tail.",
    "O(n)", "O(1)",
    ["Can you minimise the number of writes?", "What if the zeros had to go to the front instead?"],
  ),
  "reverse-linked-list": kit(
    "If you walk the list, what should each node's `next` point at instead?",
    "Point each node back at the previous one, but save the next node before you overwrite the link.",
    "Iterate with `prev`, `current` and `next`, flipping one link per step; `prev` ends as the new head.",
    "O(n)", "O(1)",
    ["Can you do it recursively? What does the call stack cost?", "How would you reverse only the part between positions `m` and `n`?"],
  ),
  "merge-two-sorted-lists": kit(
    "Which node must come first in the merged list?",
    "Repeatedly take the smaller of the two current heads. A dummy node avoids special cases.",
    "Splice nodes from a dummy head, always taking the smaller head, then attach whatever remains.",
    "O(n + m)", "O(1)",
    ["How would you merge k sorted lists?", "The recursive version is elegant. What's its space cost?"],
  ),
  "maximum-depth-of-binary-tree": kit(
    "How does a tree's depth relate to the depths of its subtrees?",
    "Depth is 1 plus the deeper subtree's depth. What's the depth of an empty tree?",
    "Recursion: `depth(node) = 1 + max(depth(left), depth(right))`, or count levels with a BFS.",
    "O(n)", "O(h)",
    ["Can you do it iteratively?", "How would you find the minimum depth instead?"],
  ),
  "invert-binary-tree": kit(
    "What does inverting do to the root's two children?",
    "Swap the children, then do the same thing to each subtree.",
    "Recursively swap left and right at every node (or process nodes with a queue).",
    "O(n)", "O(h)",
    ["Can you do it without recursion?", "How would you check whether one tree is the mirror of another?"],
  ),
  "contains-duplicate": kit(
    "What do you need to remember about the numbers you've already passed?",
    "A set gives constant-time 'have I seen this?' checks.",
    "Add numbers to a hash set as you scan; the first one already present is a duplicate.",
    "O(n)", "O(n)",
    ["Can you do it with O(1) extra space? What does that cost? (Sorting.)", "What if duplicates only count when they're at most `k` positions apart?"],
  ),
  "plus-one": kit(
    "When does adding one change more than the last digit?",
    "Walk from the right: a 9 becomes 0 and carries. When do you stop?",
    "Scan from the last digit, turning 9s into 0s until a digit can be incremented; if all were 9s, prepend a 1.",
    "O(n)", "O(1)",
    ["How would you add two numbers stored as digit arrays?", "What if the digits were in a linked list?"],
  ),
  "merge-sorted-array": kit(
    "If you fill `nums1` from the front, what goes wrong?",
    "The free space is at the end of `nums1`. Which value belongs in the very last slot?",
    "Three pointers from the back: write the larger of the two remaining tails into the last free slot.",
    "O(m + n)", "O(1)",
    ["Why does filling from the back never overwrite a value you still need?", "What if `nums1` had no extra space at the end?"],
  ),
  "majority-element": kit(
    "The majority appears more than half the time. What happens if you pair it off against other values?",
    "Cancel each occurrence against a different value. Which value must survive?",
    "Boyer–Moore voting: keep a candidate and a counter; equal values add one, others subtract one.",
    "O(n)", "O(1)",
    ["How would you find every element that appears more than n/3 times?", "How would you check that a majority really exists?"],
  ),
  "longest-common-prefix": kit(
    "The prefix can't be longer than which word?",
    "Compare all the words one column at a time and stop at the first mismatch.",
    "Vertical scan: check each position across every word until one ends or disagrees.",
    "O(S)", "O(1)",
    ["(S is the total number of characters.) Could a trie help with many queries?", "What if you had to answer for many different word lists?"],
  ),
  "fizz-buzz": kit(
    "Which check has to come first so `15` prints `FizzBuzz`?",
    "Check divisibility by both 3 and 5 before checking them separately.",
    "Loop from 1 to n, testing 15, then 3, then 5 (or concatenate the words).",
    "O(n)", "O(1)",
    ["How would you make the rules easy to extend (like 7 → `Bazz`)?", "Can you do it without the modulo operator?"],
  ),
  "palindrome-number": kit(
    "Which numbers can never be palindromes?",
    "Negatives (and numbers ending in 0, except 0) can't be. Reverse the digits mathematically and compare.",
    "Reverse the number with `% 10` and `/ 10`, or reverse only half of it to avoid overflow, and compare.",
    "O(log n)", "O(1)",
    ["(log n is the number of digits.) Can you do it without converting to a string?", "Why does reversing only half the digits avoid overflow?"],
  ),
  "reverse-string": kit(
    "Which two characters swap places first?",
    "Swap the ends and move both pointers inward until they meet.",
    "Two pointers from both ends, swapping in place.",
    "O(n)", "O(1)",
    ["Can you do it recursively? What does that cost?", "How would you reverse the order of words in a sentence instead?"],
  ),
  "pascals-triangle": kit(
    "How is each number in a row related to the row above it?",
    "Each inner value is the sum of the two values above it; the ends are always 1.",
    "Build row by row: `row[j] = prev[j - 1] + prev[j]` with 1s at both ends.",
    "O(n²)", "O(n²)",
    ["Can you return just row `k` using O(k) space?", "Can you compute a single entry directly? (Binomial coefficients.)"],
  ),
  "is-subsequence": kit(
    "Do the letters of `s` have to appear next to each other in `t`?",
    "Walk through `t` once and match the letters of `s` in order with a second pointer.",
    "Two pointers: advance through `t`, moving the `s` pointer on each match; succeed if it reaches the end.",
    "O(n)", "O(1)",
    ["What if you had millions of strings `s` to check against the same `t`?", "How would preprocessing `t` with letter positions plus binary search help?"],
  ),
  "ransom-note": kit(
    "What do you need to know about the magazine before checking the note?",
    "Count the magazine's letters, then spend them on the note.",
    "Count letters (26 slots or a map), decrement for each letter of the note, fail if any count goes negative.",
    "O(m + n)", "O(1)",
    ["What changes for Unicode text?", "What if the magazine arrived as a stream, one letter at a time?"],
  ),
  "squares-of-a-sorted-array": kit(
    "Where are the largest squares in a sorted array that has negative numbers?",
    "The biggest square is at one of the two ends. Fill the answer from the back.",
    "Two pointers from both ends, writing the larger square into the result from the back.",
    "O(n)", "O(n)",
    ["Squaring then sorting works. Why is it slower?", "Can you avoid the extra array?"],
  ),
  "middle-of-the-linked-list": kit(
    "Can you find the middle without counting the nodes first?",
    "Move one pointer twice as fast as another. Where is the slow one when the fast one finishes?",
    "Slow and fast pointers: when `fast` reaches the end, `slow` is at the middle.",
    "O(n)", "O(1)",
    ["How would you return the first middle node for even lengths?", "How do the same two pointers detect a cycle?"],
  ),
  "same-tree": kit(
    "When are two empty trees the same? When are two non-empty ones?",
    "The roots must match, and the left subtrees and right subtrees must each be the same.",
    "Recursively compare the roots, then the left subtrees, then the right subtrees.",
    "O(n)", "O(h)",
    ["Can you do it iteratively with a stack or queue?", "How would you check whether one tree is a subtree of another?"],
  ),
  "symmetric-tree": kit(
    "A tree is symmetric if its left side is a mirror of what?",
    "Compare two subtrees at a time: outer children with outer, inner with inner.",
    "A helper `mirror(a, b)`: roots equal, `a.left` mirrors `b.right` and `a.right` mirrors `b.left`.",
    "O(n)", "O(h)",
    ["Can you do it iteratively with a queue of pairs?", "How would you make a tree symmetric?"],
  ),
  "diameter-of-binary-tree": kit(
    "Does the longest path have to pass through the root?",
    "Every path bends at some highest node. Its length there is the left height plus the right height.",
    "One DFS returning each subtree's height while tracking the best `left + right` seen anywhere.",
    "O(n)", "O(h)",
    ["How would you return the path itself, not just its length?", "What changes for a tree where nodes have any number of children?"],
  ),
  "balanced-binary-tree": kit(
    "What do you need to know about each subtree to decide whether a node is balanced?",
    "Heights. Computing them top-down repeats work; can you return them bottom-up instead?",
    "Post-order DFS returning each subtree's height, or `-1` as soon as any subtree is unbalanced.",
    "O(n)", "O(h)",
    ["Checking each node's heights separately is O(n²) on a skewed tree. Why?", "How would you rebalance an unbalanced binary search tree?"],
  ),
  "search-insert-position": kit(
    "The array is sorted. What does the middle element tell you about where `target` goes?",
    "Look for the first index whose value is at least `target`.",
    "Binary search (a lower bound): when the loop ends, `low` is the insertion point.",
    "O(log n)", "O(1)",
    ["With duplicates, should it go before or after them? (Lower bound vs upper bound.)", "How would you find the last position where it could go?"],
  ),
  // ---------- Medium ----------
  "maximum-subarray": kit(
    "If the subarray ending just before here has a negative sum, is it worth keeping?",
    "Track the best sum of a subarray that ends at the current position, and the best overall.",
    "Kadane's algorithm: `current = max(num, current + num)`, keeping the maximum `current` seen.",
    "O(n)", "O(1)",
    ["How would you return the start and end of the best subarray?", "Can you solve it with divide and conquer? What does that cost?"],
  ),
  "group-anagrams": kit(
    "What could two anagrams share that you could use as a key?",
    "Give each word a signature that's the same for all of its anagrams, like its letters sorted.",
    "A hash map from each word's sorted letters (or its letter counts) to the list of words with that signature.",
    "O(n·k log k)", "O(n·k)",
    ["(k is the longest word length.) How do letter counts as a key avoid the sort?", "What would you do with extremely long strings?"],
  ),
  "longest-substring-without-repeating-characters": kit(
    "When you meet a character that's already in your window, which part of the window is still usable?",
    "Keep a window with no repeats. When a character repeats, jump the start past its previous position.",
    "A sliding window with a map from character to its last index; move the start past repeats and track the longest window.",
    "O(n)", "O(min(n, a))",
    ["(a is the alphabet size.) How would you allow at most `k` distinct characters?", "How would you return the substring itself?"],
  ),
  "product-of-array-except-self": kit(
    "Without dividing, how can you describe everything except position `i`?",
    "It's the product of everything to the left times the product of everything to the right.",
    "Two passes: fill the output with prefix products, then multiply in suffix products from the right.",
    "O(n)", "O(1)",
    ["(Extra space, not counting the output.) Why is division a bad idea here? Think about zeros.", "How would you handle zeros if division were allowed?"],
  ),
  "top-k-frequent-elements": kit(
    "What do you need to know about each number before you can rank them?",
    "Count frequencies first. Then how do you pick the k biggest counts without fully sorting?",
    "Count with a hash map, then bucket numbers by frequency and read from the highest bucket (or use a size-k min-heap).",
    "O(n)", "O(n)",
    ["How would the heap approach compare? (O(n log k).)", "What if the numbers arrived as an endless stream?"],
  ),
  "three-sum": kit(
    "If you fix the first number, what problem is left for the other two?",
    "With the array sorted, finding two numbers that add up to a value can use two pointers.",
    "Sort, then for each first number run two pointers on the rest, skipping duplicates at every level.",
    "O(n²)", "O(1)",
    ["(Extra space besides sorting and the output.) How would you find the triplet closest to a target?", "How does this generalise to 4Sum, or k numbers?"],
  ),
  "container-with-most-water": kit(
    "Start with the widest container. Which wall is limiting its height?",
    "Moving the taller wall inward can never help. What about the shorter one?",
    "Two pointers from both ends, always moving the shorter wall inward and tracking the best area.",
    "O(n)", "O(1)",
    ["Can you argue why the optimal pair is never skipped?", "How is this different from trapping rain water?"],
  ),
  "longest-consecutive-sequence": kit(
    "Sorting would work, but it's O(n log n). What structure answers 'is x - 1 here?' instantly?",
    "Put everything in a set and only start counting from numbers that begin a run.",
    "Hash set; for each `x` with no `x - 1`, count up while `x + 1` exists. Each number is visited a constant number of times.",
    "O(n)", "O(n)",
    ["Why is this still O(n) despite the inner loop?", "How would union-find solve it?"],
  ),
  "subarray-sum-equals-k": kit(
    "How can you get the sum of any subarray from running totals?",
    "A subarray ending here sums to `k` when an earlier prefix sum equals `prefix - k`.",
    "Prefix sums with a hash map counting how often each prefix sum has appeared.",
    "O(n)", "O(n)",
    ["Why doesn't a sliding window work here? (Negative numbers.)", "How would you find the longest such subarray?"],
  ),
  "merge-intervals": kit(
    "In what order would overlapping intervals be easiest to spot?",
    "Sort by start time. Then each interval either extends the last merged one or starts a new one.",
    "Sort by start, then sweep, extending the last merged interval's end when they overlap.",
    "O(n log n)", "O(n)",
    ["What if intervals arrived one at a time and you had to keep them merged?", "How would you find the most intervals overlapping at any moment?"],
  ),
  "insert-interval": kit(
    "The intervals are already sorted and don't overlap. Which ones can the new interval touch?",
    "Split the list into: before the new interval, overlapping it, and after it.",
    "One pass: copy intervals that end before it, merge the overlapping ones into it, then copy the rest.",
    "O(n)", "O(n)",
    ["Can binary search find the overlapping range faster?", "What if you had to insert many intervals one after another?"],
  ),
  "search-in-rotated-sorted-array": kit(
    "After the rotation, is any part of the array still sorted?",
    "At every middle point, one half is sorted. Can you tell whether `target` lies in that half?",
    "Binary search: find which half is sorted, then keep it if `target` falls inside its range, else the other half.",
    "O(log n)", "O(1)",
    ["What breaks if duplicates are allowed? What's the worst case then?", "How would you find the rotation point itself?"],
  ),
  "daily-temperatures": kit(
    "Which earlier days get their answer when a warm day arrives?",
    "Keep the days still waiting for a warmer day. What order are their temperatures in?",
    "A monotonic stack of indices with decreasing temperatures; each new day pops and answers every colder day.",
    "O(n)", "O(n)",
    ["Why is this O(n) even though there's a loop inside the loop?", "Could you scan from the right and jump ahead using the answers you already have?"],
  ),
  "kth-largest-element-in-an-array": kit(
    "Do you really need to sort everything to find one element?",
    "Keep only the k largest numbers seen so far. Which of them is the answer?",
    "A min-heap of size k (the answer is its top), or quickselect for linear time on average.",
    "O(n log k)", "O(k)",
    ["What's quickselect's worst case, and how do you avoid it?", "What if numbers kept arriving and you had to answer after each one?"],
  ),
  "coin-change": kit(
    "Does always taking the biggest coin first work? Try coins `[1, 3, 4]` and amount `6`.",
    "Greedy fails, so think about smaller amounts: the best for `x` builds on the best for `x - coin`.",
    "Bottom-up DP: `best[x] = 1 + min(best[x - coin])` over all coins, with unreachable amounts marked as infinity.",
    "O(a·c)", "O(a)",
    ["(a is the amount, c the number of coins.) How would you count the number of ways to make the amount instead?", "How does a breadth-first search over amounts solve the same problem?"],
  ),
  "house-robber": kit(
    "At each house you have two choices. What are they?",
    "Rob it (plus the best up to two houses back) or skip it (the best up to the previous house).",
    "DP keeping only the last two best totals: `best = max(prev, prevPrev + money)`.",
    "O(n)", "O(1)",
    ["What if the houses were arranged in a circle?", "What if the houses formed a binary tree?"],
  ),
  "word-break": kit(
    "If you know which prefixes of the string can be split into words, can you extend that?",
    "A prefix of length `i` is splittable if a shorter splittable prefix plus a dictionary word makes it.",
    "DP over prefixes with a hash set of words: `ok[i]` is true when some `ok[j]` is true and `s[j:i]` is a word.",
    "O(n²)", "O(n)",
    ["How would limiting `j` to the longest word's length speed it up?", "How would you return every possible sentence?"],
  ),
  "subsets": kit(
    "For each number, how many choices are there?",
    "Each number is either in or out, so there are 2ⁿ subsets. Build them up one number at a time.",
    "Iteratively double the list of subsets for each number (or backtrack, or count with a bitmask).",
    "O(n·2ⁿ)", "O(n·2ⁿ)",
    ["(The output itself is that size.) What changes if the input has duplicates?", "How do bitmasks map to subsets?"],
  ),
  "permutations": kit(
    "How many choices do you have for the first position? And for the second?",
    "Fill one position at a time with an unused number, then undo the choice and try the next.",
    "Backtracking with a used-array (or swapping in place), recording each full arrangement.",
    "O(n·n!)", "O(n)",
    ["(Plus the output.) What changes if the input has duplicates?", "How would you find the next permutation in place?"],
  ),
  "combination-sum": kit(
    "How do you avoid counting `[2, 3]` and `[3, 2]` as different combinations?",
    "Only allow choices at or after the current candidate, and allow the same candidate again.",
    "Backtracking over candidates in order: reuse the current number or move to the next, pruning when the sum passes the target.",
    "Exponential", "O(t)",
    ["(t is target divided by the smallest candidate: the deepest recursion.) What if each number could be used only once?", "How would you only count the combinations?"],
  ),
  "number-of-islands": kit(
    "When you find a piece of land, how do you avoid counting the same island twice?",
    "Visit all land connected to it right away and mark it.",
    "Scan the grid; for each unvisited land cell, count an island and flood-fill it with DFS or BFS.",
    "O(m·n)", "O(m·n)",
    ["How would you find the largest island's area?", "What if land appeared one cell at a time and you had to answer after each? (Union-find.)"],
  ),
  "rotting-oranges": kit(
    "If several oranges are rotten at the start, do they spread one after another or at the same time?",
    "All at once. Start a breadth-first search from every rotten orange together.",
    "Multi-source BFS: each BFS layer is one minute; at the end, any fresh orange left means `-1`.",
    "O(m·n)", "O(m·n)",
    ["Why would running a separate BFS from each rotten orange be slower?", "How would you get, for every cell, the distance to the nearest rotten orange?"],
  ),
  "course-schedule": kit(
    "When is it impossible to finish every course?",
    "When the prerequisites form a cycle. How do you detect a cycle in a directed graph?",
    "Topological sort (Kahn's algorithm): repeatedly take courses with no remaining prerequisites; success if all are taken.",
    "O(V + E)", "O(V + E)",
    ["How would you return a valid order of courses?", "How does a DFS with three colours detect the cycle instead?"],
  ),
  "number-of-connected-components": kit(
    "If you start at one node and visit everything reachable, what have you found?",
    "One component. Alternatively, merge the two ends of every edge into one group.",
    "Union-find with path compression: components = n minus the number of successful unions (DFS also works).",
    "O(V + E)", "O(V)",
    ["How would you check whether the graph is a valid tree?", "Which would you pick for a graph that keeps growing, DFS or union-find?"],
  ),
  "rotate-image": kit(
    "Where does the element at row `i`, column `j` end up after a clockwise turn?",
    "It ends up at row `j`, column `n - 1 - i`. Can two simpler moves get it there?",
    "Transpose the matrix, then reverse each row, all in place.",
    "O(n²)", "O(1)",
    ["How would you rotate counter-clockwise?", "Can you rotate layer by layer with four-way swaps instead?"],
  ),
  "remove-nth-node-from-end-of-list": kit(
    "If you knew the length, which node would you remove? Can you avoid needing the length?",
    "Keep two pointers `n` nodes apart. Where's the back one when the front one hits the end?",
    "Advance `fast` n steps, move both until `fast` ends, then unlink after `slow`; a dummy head handles removing the first node.",
    "O(n)", "O(1)",
    ["What does the two-pass version look like?", "What should happen if `n` is larger than the list?"],
  ),
  "binary-tree-level-order-traversal": kit(
    "Which data structure visits nodes in the order they were discovered?",
    "A queue. How do you know where one level ends and the next begins?",
    "BFS: at each step note the queue's size, pop exactly that many nodes as one level, and push their children.",
    "O(n)", "O(w)",
    ["(w is the widest level.) How would you produce a zigzag order?", "How would you return the levels bottom-up?"],
  ),
  "validate-binary-search-tree": kit(
    "Is it enough to compare each node with its direct children? Try a counterexample.",
    "Every node must fit inside a range set by all of its ancestors, not just its parent.",
    "DFS passing down `(low, high)` bounds, or check that an in-order traversal is strictly increasing.",
    "O(n)", "O(h)",
    ["How do the rules change if duplicates were allowed on one side?", "Can you do the in-order check iteratively?"],
  ),
  "longest-palindromic-substring": kit(
    "Every palindrome reads the same out from its middle. Where can a middle be?",
    "A middle is a character or the gap between two characters, so there are `2n - 1` centres to try.",
    "Expand around each centre while the ends match, keeping the longest palindrome found.",
    "O(n²)", "O(1)",
    ["Manacher's algorithm does it in O(n). What's the key idea?", "How would you count all palindromic substrings?"],
  ),
  "set-matrix-zeroes": kit(
    "Why can't you zero rows and columns the moment you find a zero?",
    "You'd lose information. First record which rows and columns to clear, then clear them.",
    "Record zero rows and columns (two sets, or the first row and column as markers for O(1) space), then zero in a second pass.",
    "O(m·n)", "O(1)",
    ["How does using the first row and column as markers work, and what's the catch?", "Why does zeroing immediately give wrong answers?"],
  ),
  "spiral-matrix": kit(
    "Which cells form the outer ring, and in what order?",
    "Keep four boundaries. After walking one side, move that boundary inward.",
    "Walk right, down, left and up while shrinking the top, right, bottom and left boundaries until they cross.",
    "O(m·n)", "O(1)",
    ["(Extra space besides the output.) How would you generate a spiral matrix from 1 to n²?", "What edge cases do a single row or column create?"],
  ),
  "jump-game": kit(
    "Do you need to try every possible sequence of jumps?",
    "Track the farthest index you can reach as you walk forward.",
    "Greedy: keep the farthest reach; if you stand on an index beyond it, you're stuck.",
    "O(n)", "O(1)",
    ["How would you find the minimum number of jumps?", "What does the DP version cost, and why is greedy enough?"],
  ),
  "unique-paths": kit(
    "In how many ways can you enter a cell? From which neighbours?",
    "Only from above or from the left. So each cell's count is the sum of those two counts.",
    "DP over the grid with a single rolling row (or count combinations: choose the down-moves among all moves).",
    "O(m·n)", "O(n)",
    ["What if some cells had obstacles?", "Can you compute it directly with a binomial coefficient?"],
  ),
  "longest-increasing-subsequence": kit(
    "For each element, what's the longest increasing subsequence that ends with it?",
    "That's an O(n²) DP. To go faster, keep the smallest possible tail value for each length.",
    "Patience sorting: maintain sorted tails and binary search where each number goes; the length is the answer.",
    "O(n log n)", "O(n)",
    ["How would you rebuild the subsequence itself?", "How would you count how many longest increasing subsequences there are?"],
  ),
  "decode-ways": kit(
    "How can the last digit, or the last two digits, be decoded?",
    "One digit alone (if it isn't 0) or two digits together (10 to 26). Count both cases.",
    "DP over prefixes, keeping only the last two counts: add `ways[i - 1]` and/or `ways[i - 2]` when valid.",
    "O(n)", "O(1)",
    ["What breaks if the string starts with `0`, or contains `30`?", "How would you return every decoding?"],
  ),
  "find-minimum-in-rotated-sorted-array": kit(
    "Where's the minimum relative to the rotation point?",
    "Compare the middle with the last element to tell which side of the drop you're on.",
    "Binary search: if `nums[mid] > nums[high]` the minimum is right of `mid`, otherwise at `mid` or to its left.",
    "O(log n)", "O(1)",
    ["What changes with duplicates?", "How would you tell how many times the array was rotated?"],
  ),
  "generate-parentheses": kit(
    "When are you allowed to add an opening bracket? A closing one?",
    "Open while fewer than `n` are open; close while more have opened than closed.",
    "Backtracking with two counters, so only valid strings are ever built.",
    "O(4ⁿ/√n)", "O(n)",
    ["(That's the nth Catalan number of results.) How would you only count them?", "How would you check whether a given string is balanced?"],
  ),
  "letter-combinations-of-a-phone-number": kit(
    "How many letters can each digit be?",
    "Choose a letter for the first digit, then build every combination for the rest.",
    "Backtracking over the digits (or extend a list of partial strings one digit at a time).",
    "O(n·4ⁿ)", "O(n)",
    ["(Plus the output.) What would the iterative version look like?", "How should an empty input be handled?"],
  ),
  "word-search": kit(
    "From a starting cell, how do you try to spell the rest of the word?",
    "Depth-first search to neighbouring cells, one letter per step, without reusing a cell on the current path.",
    "Try each cell as a start; DFS marks cells while they're on the path and unmarks them on the way back.",
    "O(m·n·3ᴸ)", "O(L)",
    ["(L is the word length.) How would you search for many words at once? (A trie.)", "What quick checks could rule a word out before searching?"],
  ),
  "sort-colors": kit(
    "With only three values, do you need a general sorting algorithm?",
    "Keep the 0s at the front and the 2s at the back as you scan the middle.",
    "Dutch national flag: three pointers (low, mid, high), swapping 0s forward and 2s backward in one pass.",
    "O(n)", "O(1)",
    ["Counting then rewriting takes two passes. Can you do it in one?", "How would it generalise to k colours?"],
  ),
  "evaluate-reverse-polish-notation": kit(
    "When you reach an operator, where are its two operands?",
    "They're the two most recent values. Which data structure holds those?",
    "A stack: push numbers; for an operator, pop the right then the left operand, apply it and push the result.",
    "O(n)", "O(n)",
    ["How would you convert an infix expression to RPN? (Shunting-yard.)", "How should division round, and why does it matter?"],
  ),
  "kth-smallest-element-in-a-bst": kit(
    "Which traversal visits a binary search tree's values in sorted order?",
    "An in-order traversal. Can you stop as soon as you've visited `k` nodes?",
    "Iterative in-order traversal with a stack, returning the `k`th value visited.",
    "O(h + k)", "O(h)",
    ["If the tree changed often and you asked this often, what extra data would help? (Subtree sizes.)", "Can you do it without a stack? (Morris traversal.)"],
  ),
  "binary-tree-right-side-view": kit(
    "Standing on the right, which node of each level would you see?",
    "The last node of each level in a level-order traversal.",
    "BFS level by level, recording the last node of each level (or a DFS that visits right children first).",
    "O(n)", "O(w)",
    ["How would the DFS version decide when to record a node?", "How would you get the left side view?"],
  ),
  "construct-binary-tree-from-preorder-and-inorder-traversal": kit(
    "Which traversal tells you the root right away?",
    "Preorder starts with the root, and the root's position in inorder splits the left subtree from the right.",
    "Recursion with a map from value to inorder index, consuming preorder from the front.",
    "O(n)", "O(n)",
    ["How would you build it from postorder and inorder instead?", "Why can't preorder and postorder always rebuild a unique tree?"],
  ),
  "add-two-numbers": kit(
    "How do you add two numbers by hand, column by column?",
    "The digits are stored backwards, so the lists start with the ones column. Carry as you go.",
    "Walk both lists together, adding digits plus the carry, and append a final carry node if needed.",
    "O(max(m, n))", "O(1)",
    ["(Extra space besides the result.) What if the digits were stored most significant first?", "Can you do it without reversing or modifying the inputs?"],
  ),
  "network-delay-time": kit(
    "The signal spreads along weighted edges. When does each node first hear it?",
    "That's the shortest-path time from the source. Which algorithm finds those with non-negative weights?",
    "Dijkstra's algorithm with a min-heap; the answer is the largest shortest time, or -1 if a node is unreachable.",
    "O(E log V)", "O(V + E)",
    ["Why doesn't a plain BFS work here?", "What would you use if some times could be negative?"],
  ),
  // ---------- Hard ----------
  "trapping-rain-water": kit(
    "How much water can sit on top of one particular bar?",
    "It's limited by the tallest bar on its left and the tallest on its right. Can you know both without rescanning?",
    "Two pointers moving inward with running left and right maximums; the side with the smaller maximum is settled.",
    "O(n)", "O(1)",
    ["What does the version with prefix and suffix maximum arrays look like?", "How would you trap water on a 2D height map? (A heap.)"],
  ),
  "largest-rectangle-in-histogram": kit(
    "For a given bar used as the height, how far can its rectangle stretch?",
    "Until a shorter bar on each side. Which structure finds the nearest shorter bars?",
    "A monotonic stack of increasing heights; when a shorter bar arrives, pop and score each popped bar's widest rectangle.",
    "O(n)", "O(n)",
    ["How does this solve the largest rectangle of 1s in a binary matrix?", "What would a divide-and-conquer solution cost?"],
  ),
  "sliding-window-maximum": kit(
    "When a bigger number enters the window, can any smaller number before it ever be the maximum again?",
    "No, so throw those away. Keep candidates in decreasing order.",
    "A deque of indices with decreasing values: drop expired indices from the front and smaller values from the back.",
    "O(n)", "O(k)",
    ["What does a heap-based solution cost? (O(n log k).)", "How would you track the minimum at the same time?"],
  ),
  "minimum-window-substring": kit(
    "If a window contains everything in `t`, can it get smaller?",
    "Grow the right edge until the window is valid, then shrink from the left while it stays valid.",
    "A sliding window with letter counts and a count of how many requirements are met; record the smallest valid window.",
    "O(m + n)", "O(a)",
    ["(a is the alphabet size.) How does `t` containing repeated letters change the bookkeeping?", "How would you return every minimum window?"],
  ),
  "median-of-two-sorted-arrays": kit(
    "Merging takes O(m + n). The median splits the combined numbers into two halves. Can you search for that split?",
    "Binary search a cut in the shorter array; the cut in the other array follows from the total size.",
    "Binary search on partitions until both left parts are no bigger than both right parts, then read the median off the boundary.",
    "O(log(min(m, n)))", "O(1)",
    ["How would you find the kth smallest element of two sorted arrays?", "Why search the shorter array?"],
  ),
  "merge-k-sorted-lists": kit(
    "Merging two lists is easy. How do you always know which of k heads is smallest?",
    "A min-heap of the current heads gives the smallest in O(log k).",
    "Pop the smallest head from a min-heap, append it, push its successor (or merge the lists in pairs, like merge sort).",
    "O(N log k)", "O(k)",
    ["(N is the total number of nodes.) How does merging in pairs compare?", "How would you merge sorted files too big for memory?"],
  ),
  "binary-tree-maximum-path-sum": kit(
    "A path can bend at most once. Where is the highest point of the best path?",
    "At each node, combine the best downward path on the left and on the right, ignoring negative ones.",
    "Post-order DFS returning the best downward path sum from each node, while tracking the best bent path through any node.",
    "O(n)", "O(h)",
    ["How would you return the path itself?", "What if every value were negative?"],
  ),
  "word-ladder": kit(
    "Think of each word as a node. Which words are its neighbours?",
    "Words one letter apart are connected. Which search finds the fewest steps?",
    "Breadth-first search from `beginWord`, generating neighbours by changing one letter at a time (or with wildcard patterns).",
    "O(N·L²)", "O(N·L)",
    ["(N words of length L.) How does a bidirectional BFS help?", "How would you return every shortest transformation?"],
  ),
  "n-queens": kit(
    "Each row has exactly one queen. What do you need to check when placing one?",
    "Whether its column or either diagonal is already taken. Can each check be constant time?",
    "Backtrack row by row with sets (or bitmasks) for columns and the two diagonals (`row - col` and `row + col`).",
    "O(n!)", "O(n)",
    ["How would you return the boards themselves?", "How do bitmasks make this faster?"],
  ),
  "edit-distance": kit(
    "Compare the last letters of both words. If they match, what's left? If they don't, what are your options?",
    "Insert, delete or replace, each leading to a smaller version of the same problem.",
    "DP table `d[i][j]` over prefixes, with rolling rows to save memory.",
    "O(m·n)", "O(min(m, n))",
    ["How would you list the actual edits?", "What if only insertions and deletions were allowed?"],
  ),
  "regular-expression-matching": kit(
    "What makes `*` tricky compared with `.`?",
    "A `*` can match zero copies or one more copy of the element before it. Try both, on smaller prefixes.",
    "DP over prefixes of `s` and `p` (or recursion with memoisation).",
    "O(m·n)", "O(m·n)",
    ["How does wildcard matching (`?` and `*`) differ?", "Can you shrink the table to two rows?"],
  ),
  "first-missing-positive": kit(
    "What's the largest the answer could possibly be?",
    "It's between 1 and n + 1. Can the array itself record which of those are present?",
    "Cyclic placement: swap each value `v` in `1..n` to index `v - 1`, then return the first index `i` not holding `i + 1`.",
    "O(n)", "O(1)",
    ["Why is the total number of swaps linear?", "What if you weren't allowed to modify the input?"],
  ),
  "longest-valid-parentheses": kit(
    "Where can a valid run start, and what breaks it?",
    "An unmatched `)` breaks it. Keep track of the index just before the current run.",
    "A stack of indices seeded with -1; on an unmatched `)`, the current index becomes the new base.",
    "O(n)", "O(n)",
    ["Two scans with counters (left to right, then right to left) use O(1) space. Why do you need both?", "How would you return the substring itself?"],
  ),
  "burst-balloons": kit(
    "Choosing which balloon to burst first is messy, because neighbours change. What about the last one?",
    "If balloon `i` is the last in a range, its neighbours are the range's boundaries, which never change.",
    "Interval DP on a padded array: `best[l][r]` is the max over the last balloon `i` of `best[l][i] + best[i][r] + nums[l]·nums[i]·nums[r]`.",
    "O(n³)", "O(n²)",
    ["Why does thinking about the last burst make the subproblems independent?", "Write it top-down with memoisation. What changes?"],
  ),
  "longest-increasing-path-in-a-matrix": kit(
    "The longest path starting at a cell depends on which other cells?",
    "Only on bigger neighbours, and that never forms a cycle. So each cell's answer can be cached.",
    "DFS with memoisation: `best(cell) = 1 + max(best(bigger neighbour))`, computing each cell once.",
    "O(m·n)", "O(m·n)",
    ["How would a topological sort (peeling cells layer by layer) solve it?", "What changes if the path only had to be non-decreasing?"],
  ),
  "reverse-nodes-in-k-group": kit(
    "You know how to reverse a whole list. What changes when you reverse just k nodes?",
    "Check that k nodes remain, reverse exactly those, then reconnect them to the part before and after.",
    "Iterate group by group with a dummy head, reversing k links and stitching each group to the previous tail.",
    "O(n)", "O(1)",
    ["How would you reverse the leftover nodes too?", "What does the recursive version cost in space?"],
  ),
  "candy": kit(
    "Each child depends on both neighbours. Can you handle one direction at a time?",
    "Satisfy the left neighbours in one pass and the right neighbours in a second, keeping the larger value.",
    "Two passes over the ratings (left to right, then right to left), taking the max at each child, then summing.",
    "O(n)", "O(n)",
    ["Can you do it in O(1) space by counting up and down slopes?", "What if the children sat in a circle?"],
  ),
  "basic-calculator": kit(
    "Without parentheses, how would you evaluate `1 - 2 + 3` in one pass?",
    "Keep a running result and a sign. What do you need to remember when you open a parenthesis?",
    "One scan with a stack: at `(` push the result and sign and start fresh; at `)` combine the inner result with what you pop.",
    "O(n)", "O(n)",
    ["How would you add `*` and `/` with the right precedence?", "How should unary minus, like `-(2 + 3)`, be handled?"],
  ),
  "maximal-rectangle": kit(
    "Have you solved a simpler version of this in one dimension?",
    "Treat each row as the floor of a histogram of consecutive 1s, and find the largest rectangle in each.",
    "Build the row-by-row heights and run the largest-rectangle-in-histogram stack on each row.",
    "O(m·n)", "O(n)",
    ["How would you find the largest square of 1s instead?", "How would you count all rectangles of 1s?"],
  ),
};

export function interviewKit(problem: Problem): InterviewKit | null {
  const entry = KITS[problem.slug];
  if (!entry) return null;
  return {
    hints: [entry.nudge, entry.direction, problem.hint],
    approach: entry.approach,
    time: entry.time,
    space: entry.space,
    followUps: entry.followUps,
  };
}

// For tests: every problem has a kit.
export const KIT_SLUGS = Object.keys(KITS);